// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fastly
{
    /// <summary>
    /// Provides a Fastly AI Runtime Control virtual key, used to authenticate
    /// requests to an AI service and to attribute usage and session logs back to a
    /// named key.
    /// 
    /// ## Example Usage
    /// 
    /// Basic usage:
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Fastly = Pulumi.Fastly;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var demo = new Fastly.AiRuntimeControlVirtualKey("demo", new()
    ///     {
    ///         Name = "prod website chatbot",
    ///         Model = "claude-sonnet-4-20250514",
    ///         ProviderName = "Anthropic",
    ///         UserId = "6zhNCY1236787aJIwUgN",
    ///         ExpiresAt = "2026-08-05T17:13:36Z",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// Fastly AI Runtime Control virtual keys can be imported using their key ID, e.g.
    /// 
    /// ```sh
    /// $ pulumi import fastly:index/aiRuntimeControlVirtualKey:AiRuntimeControlVirtualKey demo xxxxxxxxxxxxxxxxxxxx
    /// ```
    /// 
    /// &gt; **Note:** Since `AccessToken` is only returned by the API at creation time, it will be empty after importing an existing virtual key.
    /// </summary>
    [FastlyResourceType("fastly:index/aiRuntimeControlVirtualKey:AiRuntimeControlVirtualKey")]
    public partial class AiRuntimeControlVirtualKey : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The generated access token used to authenticate as this virtual key. Only returned by the API when the key is created.
        /// </summary>
        [Output("accessToken")]
        public Output<string> AccessToken { get; private set; } = null!;

        /// <summary>
        /// Timestamp (UTC) of when the virtual key was created.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// The display name of the user who created the virtual key.
        /// </summary>
        [Output("createdBy")]
        public Output<string> CreatedBy { get; private set; } = null!;

        /// <summary>
        /// The expiration timestamp of the virtual key, in RFC 3339 format. Once set, this value cannot be unset, only changed.
        /// </summary>
        [Output("expiresAt")]
        public Output<string?> ExpiresAt { get; private set; } = null!;

        /// <summary>
        /// Timestamp (UTC) of when the virtual key was last used.
        /// </summary>
        [Output("lastUsedAt")]
        public Output<string> LastUsedAt { get; private set; } = null!;

        /// <summary>
        /// The AI model identifier, e.g. `claude-sonnet-4-20250514`.
        /// </summary>
        [Output("model")]
        public Output<string> Model { get; private set; } = null!;

        /// <summary>
        /// A human-readable name for the virtual key.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The AI model provider name, e.g. `Anthropic`.
        /// </summary>
        [Output("providerName")]
        public Output<string> ProviderName { get; private set; } = null!;

        /// <summary>
        /// The type of the virtual key.
        /// </summary>
        [Output("type")]
        public Output<string> Type { get; private set; } = null!;

        /// <summary>
        /// Timestamp (UTC) of when the virtual key was last updated.
        /// </summary>
        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;

        /// <summary>
        /// The ID of the user creating the virtual key. Changing this forces a new virtual key to be created.
        /// </summary>
        [Output("userId")]
        public Output<string> UserId { get; private set; } = null!;


        /// <summary>
        /// Create a AiRuntimeControlVirtualKey resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public AiRuntimeControlVirtualKey(string name, AiRuntimeControlVirtualKeyArgs args, CustomResourceOptions? options = null)
            : base("fastly:index/aiRuntimeControlVirtualKey:AiRuntimeControlVirtualKey", name, args ?? new AiRuntimeControlVirtualKeyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private AiRuntimeControlVirtualKey(string name, Input<string> id, AiRuntimeControlVirtualKeyState? state = null, CustomResourceOptions? options = null)
            : base("fastly:index/aiRuntimeControlVirtualKey:AiRuntimeControlVirtualKey", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                AdditionalSecretOutputs =
                {
                    "accessToken",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing AiRuntimeControlVirtualKey resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static AiRuntimeControlVirtualKey Get(string name, Input<string> id, AiRuntimeControlVirtualKeyState? state = null, CustomResourceOptions? options = null)
        {
            return new AiRuntimeControlVirtualKey(name, id, state, options);
        }
    }

    public sealed class AiRuntimeControlVirtualKeyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The expiration timestamp of the virtual key, in RFC 3339 format. Once set, this value cannot be unset, only changed.
        /// </summary>
        [Input("expiresAt")]
        public Input<string>? ExpiresAt { get; set; }

        /// <summary>
        /// The AI model identifier, e.g. `claude-sonnet-4-20250514`.
        /// </summary>
        [Input("model", required: true)]
        public Input<string> Model { get; set; } = null!;

        /// <summary>
        /// A human-readable name for the virtual key.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The AI model provider name, e.g. `Anthropic`.
        /// </summary>
        [Input("providerName", required: true)]
        public Input<string> ProviderName { get; set; } = null!;

        /// <summary>
        /// The ID of the user creating the virtual key. Changing this forces a new virtual key to be created.
        /// </summary>
        [Input("userId", required: true)]
        public Input<string> UserId { get; set; } = null!;

        public AiRuntimeControlVirtualKeyArgs()
        {
        }
        public static new AiRuntimeControlVirtualKeyArgs Empty => new AiRuntimeControlVirtualKeyArgs();
    }

    public sealed class AiRuntimeControlVirtualKeyState : global::Pulumi.ResourceArgs
    {
        [Input("accessToken")]
        private Input<string>? _accessToken;

        /// <summary>
        /// The generated access token used to authenticate as this virtual key. Only returned by the API when the key is created.
        /// </summary>
        public Input<string>? AccessToken
        {
            get => _accessToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _accessToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Timestamp (UTC) of when the virtual key was created.
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// The display name of the user who created the virtual key.
        /// </summary>
        [Input("createdBy")]
        public Input<string>? CreatedBy { get; set; }

        /// <summary>
        /// The expiration timestamp of the virtual key, in RFC 3339 format. Once set, this value cannot be unset, only changed.
        /// </summary>
        [Input("expiresAt")]
        public Input<string>? ExpiresAt { get; set; }

        /// <summary>
        /// Timestamp (UTC) of when the virtual key was last used.
        /// </summary>
        [Input("lastUsedAt")]
        public Input<string>? LastUsedAt { get; set; }

        /// <summary>
        /// The AI model identifier, e.g. `claude-sonnet-4-20250514`.
        /// </summary>
        [Input("model")]
        public Input<string>? Model { get; set; }

        /// <summary>
        /// A human-readable name for the virtual key.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The AI model provider name, e.g. `Anthropic`.
        /// </summary>
        [Input("providerName")]
        public Input<string>? ProviderName { get; set; }

        /// <summary>
        /// The type of the virtual key.
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        /// <summary>
        /// Timestamp (UTC) of when the virtual key was last updated.
        /// </summary>
        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        /// <summary>
        /// The ID of the user creating the virtual key. Changing this forces a new virtual key to be created.
        /// </summary>
        [Input("userId")]
        public Input<string>? UserId { get; set; }

        public AiRuntimeControlVirtualKeyState()
        {
        }
        public static new AiRuntimeControlVirtualKeyState Empty => new AiRuntimeControlVirtualKeyState();
    }
}
