// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fastly
{
    /// <summary>
    /// Provides a Custom Dashboard which can be viewed in the Fastly Control Panel.
    /// 
    /// ## Import
    /// 
    /// Fastly Custom Dashboards can be imported using their ID, e.g.
    /// 
    /// ```sh
    /// $ pulumi import fastly:index/customDashboard:CustomDashboard example xxxxxxxxxxxxxxxxxxxx
    /// ```
    /// </summary>
    [FastlyResourceType("fastly:index/customDashboard:CustomDashboard")]
    public partial class CustomDashboard : global::Pulumi.CustomResource
    {
        /// <summary>
        /// A list of dashboard items.
        /// </summary>
        [Output("dashboardItems")]
        public Output<ImmutableArray<Outputs.CustomDashboardDashboardItem>> DashboardItems { get; private set; } = null!;

        /// <summary>
        /// A short description of the dashboard.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// A human-readable name.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;


        /// <summary>
        /// Create a CustomDashboard resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public CustomDashboard(string name, CustomDashboardArgs? args = null, CustomResourceOptions? options = null)
            : base("fastly:index/customDashboard:CustomDashboard", name, args ?? new CustomDashboardArgs(), MakeResourceOptions(options, ""))
        {
        }

        private CustomDashboard(string name, Input<string> id, CustomDashboardState? state = null, CustomResourceOptions? options = null)
            : base("fastly:index/customDashboard:CustomDashboard", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing CustomDashboard resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static CustomDashboard Get(string name, Input<string> id, CustomDashboardState? state = null, CustomResourceOptions? options = null)
        {
            return new CustomDashboard(name, id, state, options);
        }
    }

    public sealed class CustomDashboardArgs : global::Pulumi.ResourceArgs
    {
        [Input("dashboardItems")]
        private InputList<Inputs.CustomDashboardDashboardItemArgs>? _dashboardItems;

        /// <summary>
        /// A list of dashboard items.
        /// </summary>
        public InputList<Inputs.CustomDashboardDashboardItemArgs> DashboardItems
        {
            get => _dashboardItems ?? (_dashboardItems = new InputList<Inputs.CustomDashboardDashboardItemArgs>());
            set => _dashboardItems = value;
        }

        /// <summary>
        /// A short description of the dashboard.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// A human-readable name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public CustomDashboardArgs()
        {
        }
        public static new CustomDashboardArgs Empty => new CustomDashboardArgs();
    }

    public sealed class CustomDashboardState : global::Pulumi.ResourceArgs
    {
        [Input("dashboardItems")]
        private InputList<Inputs.CustomDashboardDashboardItemGetArgs>? _dashboardItems;

        /// <summary>
        /// A list of dashboard items.
        /// </summary>
        public InputList<Inputs.CustomDashboardDashboardItemGetArgs> DashboardItems
        {
            get => _dashboardItems ?? (_dashboardItems = new InputList<Inputs.CustomDashboardDashboardItemGetArgs>());
            set => _dashboardItems = value;
        }

        /// <summary>
        /// A short description of the dashboard.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// A human-readable name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public CustomDashboardState()
        {
        }
        public static new CustomDashboardState Empty => new CustomDashboardState();
    }
}
