// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fastly
{
    public static class GetFastlyIpRanges
    {
        /// <summary>
        /// Use this data source to get the [IP ranges](https://docs.fastly.com/guides/securing-communications/accessing-fastlys-ip-ranges) of Fastly edge nodes.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using Pulumi;
        /// using Aws = Pulumi.Aws;
        /// using Fastly = Pulumi.Fastly;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var fastly = Fastly.GetFastlyIpRanges.Invoke();
        /// 
        ///     var fromFastly = new Aws.Ec2.SecurityGroup("fromFastly", new()
        ///     {
        ///         Ingress = new[]
        ///         {
        ///             new Aws.Ec2.Inputs.SecurityGroupIngressArgs
        ///             {
        ///                 FromPort = 443,
        ///                 ToPort = 443,
        ///                 Protocol = "tcp",
        ///                 CidrBlocks = fastly.Apply(getFastlyIpRangesResult =&gt; getFastlyIpRangesResult.CidrBlocks),
        ///                 Ipv6CidrBlocks = fastly.Apply(getFastlyIpRangesResult =&gt; getFastlyIpRangesResult.Ipv6CidrBlocks),
        ///             },
        ///         },
        ///     });
        /// 
        /// });
        /// ```
        /// 
        /// [1]: https://docs.fastly.com/guides/securing-communications/accessing-fastlys-ip-ranges
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetFastlyIpRangesResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetFastlyIpRangesResult>("fastly:index/getFastlyIpRanges:getFastlyIpRanges", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetFastlyIpRangesResult
    {
        /// <summary>
        /// The lexically ordered list of ipv4 CIDR blocks.
        /// </summary>
        public readonly ImmutableArray<string> CidrBlocks;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The lexically ordered list of ipv6 CIDR blocks.
        /// </summary>
        public readonly ImmutableArray<string> Ipv6CidrBlocks;

        [OutputConstructor]
        private GetFastlyIpRangesResult(
            ImmutableArray<string> cidrBlocks,

            string id,

            ImmutableArray<string> ipv6CidrBlocks)
        {
            CidrBlocks = cidrBlocks;
            Id = id;
            Ipv6CidrBlocks = ipv6CidrBlocks;
        }
    }
}
