// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fastly
{
    public static class GetNgwafWorkspaceRules
    {
        /// <summary>
        /// Use this data source to get a Fastly Next-Gen WAF Workspace Rule.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Fastly = Pulumi.Fastly;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var workspaceRules = Fastly.GetNgwafWorkspaceRules.Invoke(new()
        ///     {
        ///         WorkspaceId = example.Id,
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["fastlyNgwafWorkspaceRulesAll"] = workspaceRules,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetNgwafWorkspaceRulesResult> InvokeAsync(GetNgwafWorkspaceRulesArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetNgwafWorkspaceRulesResult>("fastly:index/getNgwafWorkspaceRules:getNgwafWorkspaceRules", args ?? new GetNgwafWorkspaceRulesArgs(), options.WithDefaults());

        /// <summary>
        /// Use this data source to get a Fastly Next-Gen WAF Workspace Rule.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Fastly = Pulumi.Fastly;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var workspaceRules = Fastly.GetNgwafWorkspaceRules.Invoke(new()
        ///     {
        ///         WorkspaceId = example.Id,
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["fastlyNgwafWorkspaceRulesAll"] = workspaceRules,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetNgwafWorkspaceRulesResult> Invoke(GetNgwafWorkspaceRulesInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetNgwafWorkspaceRulesResult>("fastly:index/getNgwafWorkspaceRules:getNgwafWorkspaceRules", args ?? new GetNgwafWorkspaceRulesInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Use this data source to get a Fastly Next-Gen WAF Workspace Rule.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Fastly = Pulumi.Fastly;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var workspaceRules = Fastly.GetNgwafWorkspaceRules.Invoke(new()
        ///     {
        ///         WorkspaceId = example.Id,
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["fastlyNgwafWorkspaceRulesAll"] = workspaceRules,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetNgwafWorkspaceRulesResult> Invoke(GetNgwafWorkspaceRulesInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetNgwafWorkspaceRulesResult>("fastly:index/getNgwafWorkspaceRules:getNgwafWorkspaceRules", args ?? new GetNgwafWorkspaceRulesInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetNgwafWorkspaceRulesArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the workspace.
        /// </summary>
        [Input("workspaceId", required: true)]
        public string WorkspaceId { get; set; } = null!;

        public GetNgwafWorkspaceRulesArgs()
        {
        }
        public static new GetNgwafWorkspaceRulesArgs Empty => new GetNgwafWorkspaceRulesArgs();
    }

    public sealed class GetNgwafWorkspaceRulesInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the workspace.
        /// </summary>
        [Input("workspaceId", required: true)]
        public Input<string> WorkspaceId { get; set; } = null!;

        public GetNgwafWorkspaceRulesInvokeArgs()
        {
        }
        public static new GetNgwafWorkspaceRulesInvokeArgs Empty => new GetNgwafWorkspaceRulesInvokeArgs();
    }


    [OutputType]
    public sealed class GetNgwafWorkspaceRulesResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The list of rules.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetNgwafWorkspaceRulesRuleResult> Rules;
        /// <summary>
        /// The ID of the workspace.
        /// </summary>
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetNgwafWorkspaceRulesResult(
            string id,

            ImmutableArray<Outputs.GetNgwafWorkspaceRulesRuleResult> rules,

            string workspaceId)
        {
            Id = id;
            Rules = rules;
            WorkspaceId = workspaceId;
        }
    }
}
