// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fastly
{
    /// <summary>
    /// Provides a Fastly Next-Gen WAF Account Rule.\
    /// Account-level rules apply across one or more workspaces and are useful for defining shared or global WAF logic.
    /// 
    /// ## Example Usage
    /// 
    /// Basic usage:
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Fastly = Pulumi.Fastly;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Fastly.NgwafAccountRule("example", new()
    ///     {
    ///         AppliesTos = new[]
    ///         {
    ///             "*",
    ///         },
    ///         Type = "request",
    ///         Description = "example",
    ///         Enabled = true,
    ///         RequestLogging = "sampled",
    ///         GroupOperator = "all",
    ///         Actions = new[]
    ///         {
    ///             new Fastly.Inputs.NgwafAccountRuleActionArgs
    ///             {
    ///                 Type = "block",
    ///             },
    ///         },
    ///         Conditions = new[]
    ///         {
    ///             new Fastly.Inputs.NgwafAccountRuleConditionArgs
    ///             {
    ///                 Field = "ip",
    ///                 Operator = "equals",
    ///                 Value = "1.2.3.4",
    ///             },
    ///         },
    ///         GroupConditions = new[]
    ///         {
    ///             new Fastly.Inputs.NgwafAccountRuleGroupConditionArgs
    ///             {
    ///                 GroupOperator = "all",
    ///                 Conditions = new[]
    ///                 {
    ///                     new Fastly.Inputs.NgwafAccountRuleGroupConditionConditionArgs
    ///                     {
    ///                         Field = "method",
    ///                         Operator = "equals",
    ///                         Value = "POST",
    ///                     },
    ///                 },
    ///             },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// Fastly Next-Gen WAF account rules can be imported using just the rule ID, e.g.:
    /// 
    /// ```sh
    /// $ pulumi import fastly:index/ngwafAccountRule:NgwafAccountRule demo &lt;ruleID&gt;
    /// ```
    /// </summary>
    [FastlyResourceType("fastly:index/ngwafAccountRule:NgwafAccountRule")]
    public partial class NgwafAccountRule : global::Pulumi.CustomResource
    {
        /// <summary>
        /// List of actions to perform when the rule matches.
        /// </summary>
        [Output("actions")]
        public Output<ImmutableArray<Outputs.NgwafAccountRuleAction>> Actions { get; private set; } = null!;

        /// <summary>
        /// The list of workspace IDs this signal applies to, or the wildcard `*` if it applies to all workspaces.
        /// </summary>
        [Output("appliesTos")]
        public Output<ImmutableArray<string>> AppliesTos { get; private set; } = null!;

        /// <summary>
        /// Flat list of individual conditions. Each must include `Field`, `Operator`, and `Value`.
        /// </summary>
        [Output("conditions")]
        public Output<ImmutableArray<Outputs.NgwafAccountRuleCondition>> Conditions { get; private set; } = null!;

        /// <summary>
        /// The description of the rule.
        /// </summary>
        [Output("description")]
        public Output<string> Description { get; private set; } = null!;

        /// <summary>
        /// Whether the rule is currently enabled.
        /// </summary>
        [Output("enabled")]
        public Output<bool> Enabled { get; private set; } = null!;

        /// <summary>
        /// List of grouped conditions with nested logic. Each group must define a `GroupOperator` and at least one condition.
        /// </summary>
        [Output("groupConditions")]
        public Output<ImmutableArray<Outputs.NgwafAccountRuleGroupCondition>> GroupConditions { get; private set; } = null!;

        /// <summary>
        /// Logical operator to apply to group conditions. Accepted values are `Any` and `All`.
        /// </summary>
        [Output("groupOperator")]
        public Output<string?> GroupOperator { get; private set; } = null!;

        /// <summary>
        /// Block specifically for rate*limit rules.
        /// </summary>
        [Output("rateLimit")]
        public Output<Outputs.NgwafAccountRuleRateLimit?> RateLimit { get; private set; } = null!;

        /// <summary>
        /// Logging behavior for matching requests. Accepted values are `Sampled` and `None`.
        /// </summary>
        [Output("requestLogging")]
        public Output<string?> RequestLogging { get; private set; } = null!;

        /// <summary>
        /// The type of the rule. Accepted values are `Request` and `Signal`.
        /// </summary>
        [Output("type")]
        public Output<string> Type { get; private set; } = null!;


        /// <summary>
        /// Create a NgwafAccountRule resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public NgwafAccountRule(string name, NgwafAccountRuleArgs args, CustomResourceOptions? options = null)
            : base("fastly:index/ngwafAccountRule:NgwafAccountRule", name, args ?? new NgwafAccountRuleArgs(), MakeResourceOptions(options, ""))
        {
        }

        private NgwafAccountRule(string name, Input<string> id, NgwafAccountRuleState? state = null, CustomResourceOptions? options = null)
            : base("fastly:index/ngwafAccountRule:NgwafAccountRule", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing NgwafAccountRule resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static NgwafAccountRule Get(string name, Input<string> id, NgwafAccountRuleState? state = null, CustomResourceOptions? options = null)
        {
            return new NgwafAccountRule(name, id, state, options);
        }
    }

    public sealed class NgwafAccountRuleArgs : global::Pulumi.ResourceArgs
    {
        [Input("actions", required: true)]
        private InputList<Inputs.NgwafAccountRuleActionArgs>? _actions;

        /// <summary>
        /// List of actions to perform when the rule matches.
        /// </summary>
        public InputList<Inputs.NgwafAccountRuleActionArgs> Actions
        {
            get => _actions ?? (_actions = new InputList<Inputs.NgwafAccountRuleActionArgs>());
            set => _actions = value;
        }

        [Input("appliesTos", required: true)]
        private InputList<string>? _appliesTos;

        /// <summary>
        /// The list of workspace IDs this signal applies to, or the wildcard `*` if it applies to all workspaces.
        /// </summary>
        public InputList<string> AppliesTos
        {
            get => _appliesTos ?? (_appliesTos = new InputList<string>());
            set => _appliesTos = value;
        }

        [Input("conditions")]
        private InputList<Inputs.NgwafAccountRuleConditionArgs>? _conditions;

        /// <summary>
        /// Flat list of individual conditions. Each must include `Field`, `Operator`, and `Value`.
        /// </summary>
        public InputList<Inputs.NgwafAccountRuleConditionArgs> Conditions
        {
            get => _conditions ?? (_conditions = new InputList<Inputs.NgwafAccountRuleConditionArgs>());
            set => _conditions = value;
        }

        /// <summary>
        /// The description of the rule.
        /// </summary>
        [Input("description", required: true)]
        public Input<string> Description { get; set; } = null!;

        /// <summary>
        /// Whether the rule is currently enabled.
        /// </summary>
        [Input("enabled", required: true)]
        public Input<bool> Enabled { get; set; } = null!;

        [Input("groupConditions")]
        private InputList<Inputs.NgwafAccountRuleGroupConditionArgs>? _groupConditions;

        /// <summary>
        /// List of grouped conditions with nested logic. Each group must define a `GroupOperator` and at least one condition.
        /// </summary>
        public InputList<Inputs.NgwafAccountRuleGroupConditionArgs> GroupConditions
        {
            get => _groupConditions ?? (_groupConditions = new InputList<Inputs.NgwafAccountRuleGroupConditionArgs>());
            set => _groupConditions = value;
        }

        /// <summary>
        /// Logical operator to apply to group conditions. Accepted values are `Any` and `All`.
        /// </summary>
        [Input("groupOperator")]
        public Input<string>? GroupOperator { get; set; }

        /// <summary>
        /// Block specifically for rate*limit rules.
        /// </summary>
        [Input("rateLimit")]
        public Input<Inputs.NgwafAccountRuleRateLimitArgs>? RateLimit { get; set; }

        /// <summary>
        /// Logging behavior for matching requests. Accepted values are `Sampled` and `None`.
        /// </summary>
        [Input("requestLogging")]
        public Input<string>? RequestLogging { get; set; }

        /// <summary>
        /// The type of the rule. Accepted values are `Request` and `Signal`.
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public NgwafAccountRuleArgs()
        {
        }
        public static new NgwafAccountRuleArgs Empty => new NgwafAccountRuleArgs();
    }

    public sealed class NgwafAccountRuleState : global::Pulumi.ResourceArgs
    {
        [Input("actions")]
        private InputList<Inputs.NgwafAccountRuleActionGetArgs>? _actions;

        /// <summary>
        /// List of actions to perform when the rule matches.
        /// </summary>
        public InputList<Inputs.NgwafAccountRuleActionGetArgs> Actions
        {
            get => _actions ?? (_actions = new InputList<Inputs.NgwafAccountRuleActionGetArgs>());
            set => _actions = value;
        }

        [Input("appliesTos")]
        private InputList<string>? _appliesTos;

        /// <summary>
        /// The list of workspace IDs this signal applies to, or the wildcard `*` if it applies to all workspaces.
        /// </summary>
        public InputList<string> AppliesTos
        {
            get => _appliesTos ?? (_appliesTos = new InputList<string>());
            set => _appliesTos = value;
        }

        [Input("conditions")]
        private InputList<Inputs.NgwafAccountRuleConditionGetArgs>? _conditions;

        /// <summary>
        /// Flat list of individual conditions. Each must include `Field`, `Operator`, and `Value`.
        /// </summary>
        public InputList<Inputs.NgwafAccountRuleConditionGetArgs> Conditions
        {
            get => _conditions ?? (_conditions = new InputList<Inputs.NgwafAccountRuleConditionGetArgs>());
            set => _conditions = value;
        }

        /// <summary>
        /// The description of the rule.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Whether the rule is currently enabled.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        [Input("groupConditions")]
        private InputList<Inputs.NgwafAccountRuleGroupConditionGetArgs>? _groupConditions;

        /// <summary>
        /// List of grouped conditions with nested logic. Each group must define a `GroupOperator` and at least one condition.
        /// </summary>
        public InputList<Inputs.NgwafAccountRuleGroupConditionGetArgs> GroupConditions
        {
            get => _groupConditions ?? (_groupConditions = new InputList<Inputs.NgwafAccountRuleGroupConditionGetArgs>());
            set => _groupConditions = value;
        }

        /// <summary>
        /// Logical operator to apply to group conditions. Accepted values are `Any` and `All`.
        /// </summary>
        [Input("groupOperator")]
        public Input<string>? GroupOperator { get; set; }

        /// <summary>
        /// Block specifically for rate*limit rules.
        /// </summary>
        [Input("rateLimit")]
        public Input<Inputs.NgwafAccountRuleRateLimitGetArgs>? RateLimit { get; set; }

        /// <summary>
        /// Logging behavior for matching requests. Accepted values are `Sampled` and `None`.
        /// </summary>
        [Input("requestLogging")]
        public Input<string>? RequestLogging { get; set; }

        /// <summary>
        /// The type of the rule. Accepted values are `Request` and `Signal`.
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public NgwafAccountRuleState()
        {
        }
        public static new NgwafAccountRuleState Empty => new NgwafAccountRuleState();
    }
}
