// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fastly
{
    /// <summary>
    /// Provides a Fastly TSIG Key.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Fastly = Pulumi.Fastly;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // IMPORTANT: Deleting a TSIG Key requires first removing the inbound_tsig_key_id reference in any DNS Zone that uses it.
    ///     // This requires a two-step `pulumi up` as we can't guarantee deletion order.
    ///     // e.g. removal of inbound_tsig_key_id within fastly_dns_zone might not finish first.
    ///     var example = new Fastly.TsigKey("example", new()
    ///     {
    ///         Name = "example.com.",
    ///         Algorithm = "hmac-sha256",
    ///         Secret = "c2VjcmV0a2V5MTIzNDU2Nzg=",
    ///         Description = "My TSIG key",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// Fastly TSIG Keys can be imported using their Key ID, e.g.
    /// 
    /// ```sh
    /// $ pulumi import fastly:index/tsigKey:TsigKey example xxxxxxxxxxxxxxxxxxxx
    /// ```
    /// </summary>
    [FastlyResourceType("fastly:index/tsigKey:TsigKey")]
    public partial class TsigKey : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The algorithm of the TSIG key. One of: `hmac-sha224`, `hmac-sha256`, `hmac-sha384`, `hmac-sha512`.
        /// </summary>
        [Output("algorithm")]
        public Output<string> Algorithm { get; private set; } = null!;

        /// <summary>
        /// A freeform descriptive note.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// The name of the TSIG key.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The Base64 encoded secret key.
        /// </summary>
        [Output("secret")]
        public Output<string> Secret { get; private set; } = null!;


        /// <summary>
        /// Create a TsigKey resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public TsigKey(string name, TsigKeyArgs args, CustomResourceOptions? options = null)
            : base("fastly:index/tsigKey:TsigKey", name, args ?? new TsigKeyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private TsigKey(string name, Input<string> id, TsigKeyState? state = null, CustomResourceOptions? options = null)
            : base("fastly:index/tsigKey:TsigKey", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                AdditionalSecretOutputs =
                {
                    "secret",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing TsigKey resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static TsigKey Get(string name, Input<string> id, TsigKeyState? state = null, CustomResourceOptions? options = null)
        {
            return new TsigKey(name, id, state, options);
        }
    }

    public sealed class TsigKeyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The algorithm of the TSIG key. One of: `hmac-sha224`, `hmac-sha256`, `hmac-sha384`, `hmac-sha512`.
        /// </summary>
        [Input("algorithm", required: true)]
        public Input<string> Algorithm { get; set; } = null!;

        /// <summary>
        /// A freeform descriptive note.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The name of the TSIG key.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("secret", required: true)]
        private Input<string>? _secret;

        /// <summary>
        /// The Base64 encoded secret key.
        /// </summary>
        public Input<string>? Secret
        {
            get => _secret;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _secret = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public TsigKeyArgs()
        {
        }
        public static new TsigKeyArgs Empty => new TsigKeyArgs();
    }

    public sealed class TsigKeyState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The algorithm of the TSIG key. One of: `hmac-sha224`, `hmac-sha256`, `hmac-sha384`, `hmac-sha512`.
        /// </summary>
        [Input("algorithm")]
        public Input<string>? Algorithm { get; set; }

        /// <summary>
        /// A freeform descriptive note.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The name of the TSIG key.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("secret")]
        private Input<string>? _secret;

        /// <summary>
        /// The Base64 encoded secret key.
        /// </summary>
        public Input<string>? Secret
        {
            get => _secret;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _secret = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public TsigKeyState()
        {
        }
        public static new TsigKeyState Empty => new TsigKeyState();
    }
}
