// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System.Collections.Immutable;

namespace Pulumi.Fastly
{
    public static class Config
    {
        private static readonly Pulumi.Config __config = new Pulumi.Config("fastly");
        /// <summary>
        /// Fastly API Key from https://app.fastly.com/#account
        /// </summary>
        public static string? ApiKey { get; set; } = __config.Get("apiKey");

        /// <summary>
        /// Fastly API URL
        /// </summary>
        public static string? BaseUrl { get; set; } = __config.Get("baseUrl");

        /// <summary>
        /// Set this to `true` if you only need data source that does not require authentication such as `fastly_ip_ranges`
        /// </summary>
        public static bool? NoAuth { get; set; } = __config.GetBoolean("noAuth");

    }
}
