// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.fastly.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetPackageHashResult {
    /**
     * @return The contents of the Wasm deployment package as a base64 encoded string (e.g. could be provided using an input variable or via external data source output variable). Conflicts with `filename`. Exactly one of these two arguments must be specified
     * 
     */
    private @Nullable String content;
    /**
     * @return The path to the Wasm deployment package within your local filesystem. Conflicts with `content`. Exactly one of these two arguments must be specified
     * 
     */
    private @Nullable String filename;
    /**
     * @return A SHA512 hash of all files (in sorted order) within the package.
     * 
     */
    private String hash;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;

    private GetPackageHashResult() {}
    /**
     * @return The contents of the Wasm deployment package as a base64 encoded string (e.g. could be provided using an input variable or via external data source output variable). Conflicts with `filename`. Exactly one of these two arguments must be specified
     * 
     */
    public Optional<String> content() {
        return Optional.ofNullable(this.content);
    }
    /**
     * @return The path to the Wasm deployment package within your local filesystem. Conflicts with `content`. Exactly one of these two arguments must be specified
     * 
     */
    public Optional<String> filename() {
        return Optional.ofNullable(this.filename);
    }
    /**
     * @return A SHA512 hash of all files (in sorted order) within the package.
     * 
     */
    public String hash() {
        return this.hash;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetPackageHashResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String content;
        private @Nullable String filename;
        private String hash;
        private String id;
        public Builder() {}
        public Builder(GetPackageHashResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.content = defaults.content;
    	      this.filename = defaults.filename;
    	      this.hash = defaults.hash;
    	      this.id = defaults.id;
        }

        @CustomType.Setter
        public Builder content(@Nullable String content) {
            this.content = content;
            return this;
        }
        @CustomType.Setter
        public Builder filename(@Nullable String filename) {
            this.filename = filename;
            return this;
        }
        @CustomType.Setter
        public Builder hash(String hash) {
            this.hash = Objects.requireNonNull(hash);
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        public GetPackageHashResult build() {
            final var _resultValue = new GetPackageHashResult();
            _resultValue.content = content;
            _resultValue.filename = filename;
            _resultValue.hash = hash;
            _resultValue.id = id;
            return _resultValue;
        }
    }
}
