// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.fastly.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetTlsDomainResult {
    /**
     * @return Domain name to look up activations, certificates and subscriptions for.
     * 
     */
    private String domain;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    /**
     * @return IDs of the activations associated with the domain.
     * 
     */
    private List<String> tlsActivationIds;
    /**
     * @return IDs of the certificates associated with the domain.
     * 
     */
    private List<String> tlsCertificateIds;
    /**
     * @return IDs of the subscriptions associated with the domain.
     * 
     */
    private List<String> tlsSubscriptionIds;

    private GetTlsDomainResult() {}
    /**
     * @return Domain name to look up activations, certificates and subscriptions for.
     * 
     */
    public String domain() {
        return this.domain;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return IDs of the activations associated with the domain.
     * 
     */
    public List<String> tlsActivationIds() {
        return this.tlsActivationIds;
    }
    /**
     * @return IDs of the certificates associated with the domain.
     * 
     */
    public List<String> tlsCertificateIds() {
        return this.tlsCertificateIds;
    }
    /**
     * @return IDs of the subscriptions associated with the domain.
     * 
     */
    public List<String> tlsSubscriptionIds() {
        return this.tlsSubscriptionIds;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetTlsDomainResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String domain;
        private String id;
        private List<String> tlsActivationIds;
        private List<String> tlsCertificateIds;
        private List<String> tlsSubscriptionIds;
        public Builder() {}
        public Builder(GetTlsDomainResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.domain = defaults.domain;
    	      this.id = defaults.id;
    	      this.tlsActivationIds = defaults.tlsActivationIds;
    	      this.tlsCertificateIds = defaults.tlsCertificateIds;
    	      this.tlsSubscriptionIds = defaults.tlsSubscriptionIds;
        }

        @CustomType.Setter
        public Builder domain(String domain) {
            this.domain = Objects.requireNonNull(domain);
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder tlsActivationIds(List<String> tlsActivationIds) {
            this.tlsActivationIds = Objects.requireNonNull(tlsActivationIds);
            return this;
        }
        public Builder tlsActivationIds(String... tlsActivationIds) {
            return tlsActivationIds(List.of(tlsActivationIds));
        }
        @CustomType.Setter
        public Builder tlsCertificateIds(List<String> tlsCertificateIds) {
            this.tlsCertificateIds = Objects.requireNonNull(tlsCertificateIds);
            return this;
        }
        public Builder tlsCertificateIds(String... tlsCertificateIds) {
            return tlsCertificateIds(List.of(tlsCertificateIds));
        }
        @CustomType.Setter
        public Builder tlsSubscriptionIds(List<String> tlsSubscriptionIds) {
            this.tlsSubscriptionIds = Objects.requireNonNull(tlsSubscriptionIds);
            return this;
        }
        public Builder tlsSubscriptionIds(String... tlsSubscriptionIds) {
            return tlsSubscriptionIds(List.of(tlsSubscriptionIds));
        }
        public GetTlsDomainResult build() {
            final var o = new GetTlsDomainResult();
            o.domain = domain;
            o.id = id;
            o.tlsActivationIds = tlsActivationIds;
            o.tlsCertificateIds = tlsCertificateIds;
            o.tlsSubscriptionIds = tlsSubscriptionIds;
            return o;
        }
    }
}
