// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.fastly.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ServiceWafConfigurationRule {
    /**
     * @return The Web Application Firewall rule&#39;s modsecurity ID
     * 
     */
    private Integer modsecRuleId;
    /**
     * @return The Web Application Firewall rule&#39;s revision. The latest revision will be used if this is not provided
     * 
     */
    private @Nullable Integer revision;
    /**
     * @return The Web Application Firewall rule&#39;s status. Allowed values are (`log`, `block` and `score`)
     * 
     */
    private String status;

    private ServiceWafConfigurationRule() {}
    /**
     * @return The Web Application Firewall rule&#39;s modsecurity ID
     * 
     */
    public Integer modsecRuleId() {
        return this.modsecRuleId;
    }
    /**
     * @return The Web Application Firewall rule&#39;s revision. The latest revision will be used if this is not provided
     * 
     */
    public Optional<Integer> revision() {
        return Optional.ofNullable(this.revision);
    }
    /**
     * @return The Web Application Firewall rule&#39;s status. Allowed values are (`log`, `block` and `score`)
     * 
     */
    public String status() {
        return this.status;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ServiceWafConfigurationRule defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Integer modsecRuleId;
        private @Nullable Integer revision;
        private String status;
        public Builder() {}
        public Builder(ServiceWafConfigurationRule defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.modsecRuleId = defaults.modsecRuleId;
    	      this.revision = defaults.revision;
    	      this.status = defaults.status;
        }

        @CustomType.Setter
        public Builder modsecRuleId(Integer modsecRuleId) {
            this.modsecRuleId = Objects.requireNonNull(modsecRuleId);
            return this;
        }
        @CustomType.Setter
        public Builder revision(@Nullable Integer revision) {
            this.revision = revision;
            return this;
        }
        @CustomType.Setter
        public Builder status(String status) {
            this.status = Objects.requireNonNull(status);
            return this;
        }
        public ServiceWafConfigurationRule build() {
            final var o = new ServiceWafConfigurationRule();
            o.modsecRuleId = modsecRuleId;
            o.revision = revision;
            o.status = status;
            return o;
        }
    }
}
