// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package fastly

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-fastly/sdk/v11/go/fastly/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Domain service links are for managing versionless domains for services. The link associates an existing service
// with an existing domain, but doesn't create or delete either resource.
//
// If you are managing your versionless domain with a service link, you may not also use a `resourceFastlyDomain` block as well.
//
// ## Import
//
// Domain service links can be imported using the domain ID, e.g.
//
// ```sh
// $ pulumi import fastly:index/domainServiceLink:DomainServiceLink example <domain_id>
// ```
type DomainServiceLink struct {
	pulumi.CustomResourceState

	// The Domain Identifier of the versionless domain being linked (UUID).
	DomainId pulumi.StringOutput `pulumi:"domainId"`
	// The serviceId associated with your domain
	ServiceId pulumi.StringOutput `pulumi:"serviceId"`
}

// NewDomainServiceLink registers a new resource with the given unique name, arguments, and options.
func NewDomainServiceLink(ctx *pulumi.Context,
	name string, args *DomainServiceLinkArgs, opts ...pulumi.ResourceOption) (*DomainServiceLink, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.DomainId == nil {
		return nil, errors.New("invalid value for required argument 'DomainId'")
	}
	if args.ServiceId == nil {
		return nil, errors.New("invalid value for required argument 'ServiceId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DomainServiceLink
	err := ctx.RegisterResource("fastly:index/domainServiceLink:DomainServiceLink", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDomainServiceLink gets an existing DomainServiceLink resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDomainServiceLink(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DomainServiceLinkState, opts ...pulumi.ResourceOption) (*DomainServiceLink, error) {
	var resource DomainServiceLink
	err := ctx.ReadResource("fastly:index/domainServiceLink:DomainServiceLink", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DomainServiceLink resources.
type domainServiceLinkState struct {
	// The Domain Identifier of the versionless domain being linked (UUID).
	DomainId *string `pulumi:"domainId"`
	// The serviceId associated with your domain
	ServiceId *string `pulumi:"serviceId"`
}

type DomainServiceLinkState struct {
	// The Domain Identifier of the versionless domain being linked (UUID).
	DomainId pulumi.StringPtrInput
	// The serviceId associated with your domain
	ServiceId pulumi.StringPtrInput
}

func (DomainServiceLinkState) ElementType() reflect.Type {
	return reflect.TypeOf((*domainServiceLinkState)(nil)).Elem()
}

type domainServiceLinkArgs struct {
	// The Domain Identifier of the versionless domain being linked (UUID).
	DomainId string `pulumi:"domainId"`
	// The serviceId associated with your domain
	ServiceId string `pulumi:"serviceId"`
}

// The set of arguments for constructing a DomainServiceLink resource.
type DomainServiceLinkArgs struct {
	// The Domain Identifier of the versionless domain being linked (UUID).
	DomainId pulumi.StringInput
	// The serviceId associated with your domain
	ServiceId pulumi.StringInput
}

func (DomainServiceLinkArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*domainServiceLinkArgs)(nil)).Elem()
}

type DomainServiceLinkInput interface {
	pulumi.Input

	ToDomainServiceLinkOutput() DomainServiceLinkOutput
	ToDomainServiceLinkOutputWithContext(ctx context.Context) DomainServiceLinkOutput
}

func (*DomainServiceLink) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainServiceLink)(nil)).Elem()
}

func (i *DomainServiceLink) ToDomainServiceLinkOutput() DomainServiceLinkOutput {
	return i.ToDomainServiceLinkOutputWithContext(context.Background())
}

func (i *DomainServiceLink) ToDomainServiceLinkOutputWithContext(ctx context.Context) DomainServiceLinkOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainServiceLinkOutput)
}

// DomainServiceLinkArrayInput is an input type that accepts DomainServiceLinkArray and DomainServiceLinkArrayOutput values.
// You can construct a concrete instance of `DomainServiceLinkArrayInput` via:
//
//	DomainServiceLinkArray{ DomainServiceLinkArgs{...} }
type DomainServiceLinkArrayInput interface {
	pulumi.Input

	ToDomainServiceLinkArrayOutput() DomainServiceLinkArrayOutput
	ToDomainServiceLinkArrayOutputWithContext(context.Context) DomainServiceLinkArrayOutput
}

type DomainServiceLinkArray []DomainServiceLinkInput

func (DomainServiceLinkArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DomainServiceLink)(nil)).Elem()
}

func (i DomainServiceLinkArray) ToDomainServiceLinkArrayOutput() DomainServiceLinkArrayOutput {
	return i.ToDomainServiceLinkArrayOutputWithContext(context.Background())
}

func (i DomainServiceLinkArray) ToDomainServiceLinkArrayOutputWithContext(ctx context.Context) DomainServiceLinkArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainServiceLinkArrayOutput)
}

// DomainServiceLinkMapInput is an input type that accepts DomainServiceLinkMap and DomainServiceLinkMapOutput values.
// You can construct a concrete instance of `DomainServiceLinkMapInput` via:
//
//	DomainServiceLinkMap{ "key": DomainServiceLinkArgs{...} }
type DomainServiceLinkMapInput interface {
	pulumi.Input

	ToDomainServiceLinkMapOutput() DomainServiceLinkMapOutput
	ToDomainServiceLinkMapOutputWithContext(context.Context) DomainServiceLinkMapOutput
}

type DomainServiceLinkMap map[string]DomainServiceLinkInput

func (DomainServiceLinkMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DomainServiceLink)(nil)).Elem()
}

func (i DomainServiceLinkMap) ToDomainServiceLinkMapOutput() DomainServiceLinkMapOutput {
	return i.ToDomainServiceLinkMapOutputWithContext(context.Background())
}

func (i DomainServiceLinkMap) ToDomainServiceLinkMapOutputWithContext(ctx context.Context) DomainServiceLinkMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainServiceLinkMapOutput)
}

type DomainServiceLinkOutput struct{ *pulumi.OutputState }

func (DomainServiceLinkOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainServiceLink)(nil)).Elem()
}

func (o DomainServiceLinkOutput) ToDomainServiceLinkOutput() DomainServiceLinkOutput {
	return o
}

func (o DomainServiceLinkOutput) ToDomainServiceLinkOutputWithContext(ctx context.Context) DomainServiceLinkOutput {
	return o
}

// The Domain Identifier of the versionless domain being linked (UUID).
func (o DomainServiceLinkOutput) DomainId() pulumi.StringOutput {
	return o.ApplyT(func(v *DomainServiceLink) pulumi.StringOutput { return v.DomainId }).(pulumi.StringOutput)
}

// The serviceId associated with your domain
func (o DomainServiceLinkOutput) ServiceId() pulumi.StringOutput {
	return o.ApplyT(func(v *DomainServiceLink) pulumi.StringOutput { return v.ServiceId }).(pulumi.StringOutput)
}

type DomainServiceLinkArrayOutput struct{ *pulumi.OutputState }

func (DomainServiceLinkArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DomainServiceLink)(nil)).Elem()
}

func (o DomainServiceLinkArrayOutput) ToDomainServiceLinkArrayOutput() DomainServiceLinkArrayOutput {
	return o
}

func (o DomainServiceLinkArrayOutput) ToDomainServiceLinkArrayOutputWithContext(ctx context.Context) DomainServiceLinkArrayOutput {
	return o
}

func (o DomainServiceLinkArrayOutput) Index(i pulumi.IntInput) DomainServiceLinkOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *DomainServiceLink {
		return vs[0].([]*DomainServiceLink)[vs[1].(int)]
	}).(DomainServiceLinkOutput)
}

type DomainServiceLinkMapOutput struct{ *pulumi.OutputState }

func (DomainServiceLinkMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DomainServiceLink)(nil)).Elem()
}

func (o DomainServiceLinkMapOutput) ToDomainServiceLinkMapOutput() DomainServiceLinkMapOutput {
	return o
}

func (o DomainServiceLinkMapOutput) ToDomainServiceLinkMapOutputWithContext(ctx context.Context) DomainServiceLinkMapOutput {
	return o
}

func (o DomainServiceLinkMapOutput) MapIndex(k pulumi.StringInput) DomainServiceLinkOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *DomainServiceLink {
		return vs[0].(map[string]*DomainServiceLink)[vs[1].(string)]
	}).(DomainServiceLinkOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DomainServiceLinkInput)(nil)).Elem(), &DomainServiceLink{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainServiceLinkArrayInput)(nil)).Elem(), DomainServiceLinkArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainServiceLinkMapInput)(nil)).Elem(), DomainServiceLinkMap{})
	pulumi.RegisterOutputType(DomainServiceLinkOutput{})
	pulumi.RegisterOutputType(DomainServiceLinkArrayOutput{})
	pulumi.RegisterOutputType(DomainServiceLinkMapOutput{})
}
