// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package fastly

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-fastly/sdk/v11/go/fastly/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use this data source to get a Fastly Next-Gen WAF Alert Datadog integration.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-fastly/sdk/v11/go/fastly"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := fastly.LookupNgwafAlertDatadogIntegration(ctx, &fastly.LookupNgwafAlertDatadogIntegrationArgs{
//				WorkspaceId: testRedactionsWorkspace.Id,
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("ngwafDatadogAlertsAll", datadogAlerts)
//			return nil
//		})
//	}
//
// ```
func LookupNgwafAlertDatadogIntegration(ctx *pulumi.Context, args *LookupNgwafAlertDatadogIntegrationArgs, opts ...pulumi.InvokeOption) (*LookupNgwafAlertDatadogIntegrationResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupNgwafAlertDatadogIntegrationResult
	err := ctx.Invoke("fastly:index/getNgwafAlertDatadogIntegration:getNgwafAlertDatadogIntegration", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNgwafAlertDatadogIntegration.
type LookupNgwafAlertDatadogIntegrationArgs struct {
	// The ID of the workspace.
	WorkspaceId string `pulumi:"workspaceId"`
}

// A collection of values returned by getNgwafAlertDatadogIntegration.
type LookupNgwafAlertDatadogIntegrationResult struct {
	// List of all Datadog alerts for a workspace.
	DatadogAlerts []GetNgwafAlertDatadogIntegrationDatadogAlert `pulumi:"datadogAlerts"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The ID of the workspace.
	WorkspaceId string `pulumi:"workspaceId"`
}

func LookupNgwafAlertDatadogIntegrationOutput(ctx *pulumi.Context, args LookupNgwafAlertDatadogIntegrationOutputArgs, opts ...pulumi.InvokeOption) LookupNgwafAlertDatadogIntegrationResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupNgwafAlertDatadogIntegrationResultOutput, error) {
			args := v.(LookupNgwafAlertDatadogIntegrationArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("fastly:index/getNgwafAlertDatadogIntegration:getNgwafAlertDatadogIntegration", args, LookupNgwafAlertDatadogIntegrationResultOutput{}, options).(LookupNgwafAlertDatadogIntegrationResultOutput), nil
		}).(LookupNgwafAlertDatadogIntegrationResultOutput)
}

// A collection of arguments for invoking getNgwafAlertDatadogIntegration.
type LookupNgwafAlertDatadogIntegrationOutputArgs struct {
	// The ID of the workspace.
	WorkspaceId pulumi.StringInput `pulumi:"workspaceId"`
}

func (LookupNgwafAlertDatadogIntegrationOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNgwafAlertDatadogIntegrationArgs)(nil)).Elem()
}

// A collection of values returned by getNgwafAlertDatadogIntegration.
type LookupNgwafAlertDatadogIntegrationResultOutput struct{ *pulumi.OutputState }

func (LookupNgwafAlertDatadogIntegrationResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNgwafAlertDatadogIntegrationResult)(nil)).Elem()
}

func (o LookupNgwafAlertDatadogIntegrationResultOutput) ToLookupNgwafAlertDatadogIntegrationResultOutput() LookupNgwafAlertDatadogIntegrationResultOutput {
	return o
}

func (o LookupNgwafAlertDatadogIntegrationResultOutput) ToLookupNgwafAlertDatadogIntegrationResultOutputWithContext(ctx context.Context) LookupNgwafAlertDatadogIntegrationResultOutput {
	return o
}

// List of all Datadog alerts for a workspace.
func (o LookupNgwafAlertDatadogIntegrationResultOutput) DatadogAlerts() GetNgwafAlertDatadogIntegrationDatadogAlertArrayOutput {
	return o.ApplyT(func(v LookupNgwafAlertDatadogIntegrationResult) []GetNgwafAlertDatadogIntegrationDatadogAlert {
		return v.DatadogAlerts
	}).(GetNgwafAlertDatadogIntegrationDatadogAlertArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupNgwafAlertDatadogIntegrationResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNgwafAlertDatadogIntegrationResult) string { return v.Id }).(pulumi.StringOutput)
}

// The ID of the workspace.
func (o LookupNgwafAlertDatadogIntegrationResultOutput) WorkspaceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNgwafAlertDatadogIntegrationResult) string { return v.WorkspaceId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNgwafAlertDatadogIntegrationResultOutput{})
}
