// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package fastly

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-fastly/sdk/v11/go/fastly/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use this data source to get a Fastly Next-Gen WAF Alert Mailing List integration.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-fastly/sdk/v11/go/fastly"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := fastly.LookupNgwafAlertJiraIntegration(ctx, &fastly.LookupNgwafAlertJiraIntegrationArgs{
//				WorkspaceId: testRedactionsWorkspace.Id,
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("ngwafJiraAlertsAll", jiraAlerts)
//			return nil
//		})
//	}
//
// ```
func LookupNgwafAlertMailingListIntegration(ctx *pulumi.Context, args *LookupNgwafAlertMailingListIntegrationArgs, opts ...pulumi.InvokeOption) (*LookupNgwafAlertMailingListIntegrationResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupNgwafAlertMailingListIntegrationResult
	err := ctx.Invoke("fastly:index/getNgwafAlertMailingListIntegration:getNgwafAlertMailingListIntegration", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNgwafAlertMailingListIntegration.
type LookupNgwafAlertMailingListIntegrationArgs struct {
	// The ID of the workspace.
	WorkspaceId string `pulumi:"workspaceId"`
}

// A collection of values returned by getNgwafAlertMailingListIntegration.
type LookupNgwafAlertMailingListIntegrationResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// List of all Mailing List alerts for a workspace.
	MailingListAlerts []GetNgwafAlertMailingListIntegrationMailingListAlert `pulumi:"mailingListAlerts"`
	// The ID of the workspace.
	WorkspaceId string `pulumi:"workspaceId"`
}

func LookupNgwafAlertMailingListIntegrationOutput(ctx *pulumi.Context, args LookupNgwafAlertMailingListIntegrationOutputArgs, opts ...pulumi.InvokeOption) LookupNgwafAlertMailingListIntegrationResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupNgwafAlertMailingListIntegrationResultOutput, error) {
			args := v.(LookupNgwafAlertMailingListIntegrationArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("fastly:index/getNgwafAlertMailingListIntegration:getNgwafAlertMailingListIntegration", args, LookupNgwafAlertMailingListIntegrationResultOutput{}, options).(LookupNgwafAlertMailingListIntegrationResultOutput), nil
		}).(LookupNgwafAlertMailingListIntegrationResultOutput)
}

// A collection of arguments for invoking getNgwafAlertMailingListIntegration.
type LookupNgwafAlertMailingListIntegrationOutputArgs struct {
	// The ID of the workspace.
	WorkspaceId pulumi.StringInput `pulumi:"workspaceId"`
}

func (LookupNgwafAlertMailingListIntegrationOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNgwafAlertMailingListIntegrationArgs)(nil)).Elem()
}

// A collection of values returned by getNgwafAlertMailingListIntegration.
type LookupNgwafAlertMailingListIntegrationResultOutput struct{ *pulumi.OutputState }

func (LookupNgwafAlertMailingListIntegrationResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNgwafAlertMailingListIntegrationResult)(nil)).Elem()
}

func (o LookupNgwafAlertMailingListIntegrationResultOutput) ToLookupNgwafAlertMailingListIntegrationResultOutput() LookupNgwafAlertMailingListIntegrationResultOutput {
	return o
}

func (o LookupNgwafAlertMailingListIntegrationResultOutput) ToLookupNgwafAlertMailingListIntegrationResultOutputWithContext(ctx context.Context) LookupNgwafAlertMailingListIntegrationResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o LookupNgwafAlertMailingListIntegrationResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNgwafAlertMailingListIntegrationResult) string { return v.Id }).(pulumi.StringOutput)
}

// List of all Mailing List alerts for a workspace.
func (o LookupNgwafAlertMailingListIntegrationResultOutput) MailingListAlerts() GetNgwafAlertMailingListIntegrationMailingListAlertArrayOutput {
	return o.ApplyT(func(v LookupNgwafAlertMailingListIntegrationResult) []GetNgwafAlertMailingListIntegrationMailingListAlert {
		return v.MailingListAlerts
	}).(GetNgwafAlertMailingListIntegrationMailingListAlertArrayOutput)
}

// The ID of the workspace.
func (o LookupNgwafAlertMailingListIntegrationResultOutput) WorkspaceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNgwafAlertMailingListIntegrationResult) string { return v.WorkspaceId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNgwafAlertMailingListIntegrationResultOutput{})
}
