// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package fastly

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-fastly/sdk/v8/go/fastly/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetVclSnippets(ctx *pulumi.Context, args *GetVclSnippetsArgs, opts ...pulumi.InvokeOption) (*GetVclSnippetsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetVclSnippetsResult
	err := ctx.Invoke("fastly:index/getVclSnippets:getVclSnippets", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getVclSnippets.
type GetVclSnippetsArgs struct {
	ServiceId      string `pulumi:"serviceId"`
	ServiceVersion int    `pulumi:"serviceVersion"`
}

// A collection of values returned by getVclSnippets.
type GetVclSnippetsResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id             string                     `pulumi:"id"`
	ServiceId      string                     `pulumi:"serviceId"`
	ServiceVersion int                        `pulumi:"serviceVersion"`
	VclSnippets    []GetVclSnippetsVclSnippet `pulumi:"vclSnippets"`
}

func GetVclSnippetsOutput(ctx *pulumi.Context, args GetVclSnippetsOutputArgs, opts ...pulumi.InvokeOption) GetVclSnippetsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetVclSnippetsResult, error) {
			args := v.(GetVclSnippetsArgs)
			r, err := GetVclSnippets(ctx, &args, opts...)
			var s GetVclSnippetsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetVclSnippetsResultOutput)
}

// A collection of arguments for invoking getVclSnippets.
type GetVclSnippetsOutputArgs struct {
	ServiceId      pulumi.StringInput `pulumi:"serviceId"`
	ServiceVersion pulumi.IntInput    `pulumi:"serviceVersion"`
}

func (GetVclSnippetsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVclSnippetsArgs)(nil)).Elem()
}

// A collection of values returned by getVclSnippets.
type GetVclSnippetsResultOutput struct{ *pulumi.OutputState }

func (GetVclSnippetsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVclSnippetsResult)(nil)).Elem()
}

func (o GetVclSnippetsResultOutput) ToGetVclSnippetsResultOutput() GetVclSnippetsResultOutput {
	return o
}

func (o GetVclSnippetsResultOutput) ToGetVclSnippetsResultOutputWithContext(ctx context.Context) GetVclSnippetsResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetVclSnippetsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetVclSnippetsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetVclSnippetsResultOutput) ServiceId() pulumi.StringOutput {
	return o.ApplyT(func(v GetVclSnippetsResult) string { return v.ServiceId }).(pulumi.StringOutput)
}

func (o GetVclSnippetsResultOutput) ServiceVersion() pulumi.IntOutput {
	return o.ApplyT(func(v GetVclSnippetsResult) int { return v.ServiceVersion }).(pulumi.IntOutput)
}

func (o GetVclSnippetsResultOutput) VclSnippets() GetVclSnippetsVclSnippetArrayOutput {
	return o.ApplyT(func(v GetVclSnippetsResult) []GetVclSnippetsVclSnippet { return v.VclSnippets }).(GetVclSnippetsVclSnippetArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetVclSnippetsResultOutput{})
}
