// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fastly.Outputs
{

    [OutputType]
    public sealed class GetAiRuntimeControlVirtualKeysVirtualKeyResult
    {
        /// <summary>
        /// Timestamp (UTC) of when the virtual key was created.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// The display name of the user who created the virtual key.
        /// </summary>
        public readonly string CreatedBy;
        /// <summary>
        /// The ID of the customer that owns the virtual key.
        /// </summary>
        public readonly string CustomerId;
        /// <summary>
        /// Timestamp (UTC) of when the virtual key was deleted, if applicable.
        /// </summary>
        public readonly string DeletedAt;
        /// <summary>
        /// The expiration timestamp of the virtual key, if any.
        /// </summary>
        public readonly string ExpiresAt;
        /// <summary>
        /// The ID of the virtual key.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Timestamp (UTC) of when the virtual key was last used, if applicable.
        /// </summary>
        public readonly string LastUsedAt;
        /// <summary>
        /// The AI model identifier.
        /// </summary>
        public readonly string Model;
        /// <summary>
        /// The human-readable name of the virtual key.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The AI model provider name.
        /// </summary>
        public readonly string Provider;
        /// <summary>
        /// The type of the virtual key.
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// Timestamp (UTC) of when the virtual key was last updated.
        /// </summary>
        public readonly string UpdatedAt;
        /// <summary>
        /// The ID of the user who created the virtual key.
        /// </summary>
        public readonly string UserId;
        /// <summary>
        /// The display name of the user who created the virtual key.
        /// </summary>
        public readonly string UserName;

        [OutputConstructor]
        private GetAiRuntimeControlVirtualKeysVirtualKeyResult(
            string createdAt,

            string createdBy,

            string customerId,

            string deletedAt,

            string expiresAt,

            string id,

            string lastUsedAt,

            string model,

            string name,

            string provider,

            string type,

            string updatedAt,

            string userId,

            string userName)
        {
            CreatedAt = createdAt;
            CreatedBy = createdBy;
            CustomerId = customerId;
            DeletedAt = deletedAt;
            ExpiresAt = expiresAt;
            Id = id;
            LastUsedAt = lastUsedAt;
            Model = model;
            Name = name;
            Provider = provider;
            Type = type;
            UpdatedAt = updatedAt;
            UserId = userId;
            UserName = userName;
        }
    }
}
