// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fastly.Outputs
{

    [OutputType]
    public sealed class ServiceComputeLoggingBigquery
    {
        /// <summary>
        /// The google account name used to obtain temporary credentials (default none). Not required if 'email' and 'secret_key' are provided. You may optionally provide this via an environment variable, `FASTLY_GCS_ACCOUNT_NAME`.
        /// </summary>
        public readonly string? AccountName;
        /// <summary>
        /// The ID of your BigQuery dataset
        /// </summary>
        public readonly string Dataset;
        /// <summary>
        /// The email for the service account with write access to your BigQuery dataset. If not provided, this will be pulled from a `FASTLY_BQ_EMAIL` environment variable
        /// </summary>
        public readonly string Email;
        /// <summary>
        /// A unique name to identify this BigQuery logging endpoint. It is important to note that changing this attribute will delete and recreate the resource
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Region where logs will be processed before streaming to BigQuery. Valid values are 'none', 'us' and 'eu'.
        /// </summary>
        public readonly string? ProcessingRegion;
        /// <summary>
        /// The ID of your GCP project
        /// </summary>
        public readonly string ProjectId;
        /// <summary>
        /// The secret key associated with the service account that has write access to your BigQuery table. If not provided, this will be pulled from the `FASTLY_BQ_SECRET_KEY` environment variable. Typical format for this is a private key in a string with newlines
        /// </summary>
        public readonly string SecretKey;
        /// <summary>
        /// The ID of your BigQuery table
        /// </summary>
        public readonly string Table;
        /// <summary>
        /// BigQuery table name suffix template
        /// </summary>
        public readonly string? Template;

        [OutputConstructor]
        private ServiceComputeLoggingBigquery(
            string? accountName,

            string dataset,

            string email,

            string name,

            string? processingRegion,

            string projectId,

            string secretKey,

            string table,

            string? template)
        {
            AccountName = accountName;
            Dataset = dataset;
            Email = email;
            Name = name;
            ProcessingRegion = processingRegion;
            ProjectId = projectId;
            SecretKey = secretKey;
            Table = table;
            Template = template;
        }
    }
}
