// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fastly.Outputs
{

    [OutputType]
    public sealed class ServiceComputeProductEnablement
    {
        /// <summary>
        /// Enable Fanout support
        /// </summary>
        public readonly bool? Fanout;
        /// <summary>
        /// Used internally by the provider to identify modified settings
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// Enable WebSockets support
        /// </summary>
        public readonly bool? Websockets;

        [OutputConstructor]
        private ServiceComputeProductEnablement(
            bool? fanout,

            string? name,

            bool? websockets)
        {
            Fanout = fanout;
            Name = name;
            Websockets = websockets;
        }
    }
}
