// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fastly.Outputs
{

    [OutputType]
    public sealed class Servicev1Snippet
    {
        /// <summary>
        /// The VCL code that specifies exactly what the snippet does
        /// </summary>
        public readonly string Content;
        /// <summary>
        /// A name that is unique across "regular" and "dynamic" VCL Snippet configuration blocks. It is important to note that changing this attribute will delete and recreate the resource
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Priority determines the ordering for multiple snippets. Lower numbers execute first. Defaults to `100`
        /// </summary>
        public readonly int? Priority;
        /// <summary>
        /// The location in generated VCL where the snippet should be placed (can be one of `init`, `recv`, `hit`, `miss`, `pass`, `fetch`, `error`, `deliver`, `log` or `none`)
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private Servicev1Snippet(
            string content,

            string name,

            int? priority,

            string type)
        {
            Content = content;
            Name = name;
            Priority = priority;
            Type = type;
        }
    }
}
