// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fastly.Outputs
{

    [OutputType]
    public sealed class Servicev1Condition
    {
        /// <summary>
        /// The unique name for the condition. It is important to note that changing this attribute will delete and recreate the resource
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// A number used to determine the order in which multiple conditions execute. Lower numbers execute first. Default `10`
        /// </summary>
        public readonly int? Priority;
        /// <summary>
        /// The statement used to determine if the condition is met
        /// </summary>
        public readonly string Statement;
        /// <summary>
        /// Type of condition, either `REQUEST` (req), `RESPONSE` (req, resp), or `CACHE` (req, beresp)
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private Servicev1Condition(
            string name,

            int? priority,

            string statement,

            string type)
        {
            Name = name;
            Priority = priority;
            Statement = statement;
            Type = type;
        }
    }
}
