// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fastly.Outputs
{

    [OutputType]
    public sealed class ServiceComputeProductEnablementNgwaf
    {
        /// <summary>
        /// Enable Next-Gen WAF support
        /// </summary>
        public readonly bool Enabled;
        /// <summary>
        /// The percentage of traffic to inspect
        /// </summary>
        public readonly int? TrafficRamp;
        /// <summary>
        /// The workspace to link
        /// </summary>
        public readonly string WorkspaceId;

        [OutputConstructor]
        private ServiceComputeProductEnablementNgwaf(
            bool enabled,

            int? trafficRamp,

            string workspaceId)
        {
            Enabled = enabled;
            TrafficRamp = trafficRamp;
            WorkspaceId = workspaceId;
        }
    }
}
