// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fastly.Outputs
{

    [OutputType]
    public sealed class ServiceComputeLoggingOpenstack
    {
        /// <summary>
        /// Your OpenStack account access key
        /// </summary>
        public readonly string AccessKey;
        /// <summary>
        /// The name of your OpenStack container
        /// </summary>
        public readonly string BucketName;
        /// <summary>
        /// What level of Gzip encoding to have when dumping logs (default `0`, no compression)
        /// </summary>
        public readonly int? GzipLevel;
        /// <summary>
        /// How the message should be formatted; one of: `classic`, `loggly`, `logplex` or `blank`. Default `classic`. [Fastly Documentation](https://developer.fastly.com/reference/api/logging/gcs/)
        /// </summary>
        public readonly string? MessageType;
        /// <summary>
        /// The unique name of the OpenStack logging endpoint. It is important to note that changing this attribute will delete and recreate the resource
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Path to store the files. Must end with a trailing slash. If this field is left empty, the files will be saved in the bucket's root path
        /// </summary>
        public readonly string? Path;
        /// <summary>
        /// How frequently the logs should be transferred, in seconds. Default `3600`
        /// </summary>
        public readonly int? Period;
        /// <summary>
        /// A PGP public key that Fastly will use to encrypt your log files before writing them to disk
        /// </summary>
        public readonly string? PublicKey;
        /// <summary>
        /// specified timestamp formatting (default `%Y-%m-%dT%H:%M:%S.000`)
        /// </summary>
        public readonly string? TimestampFormat;
        /// <summary>
        /// Your OpenStack auth url
        /// </summary>
        public readonly string Url;
        /// <summary>
        /// The username for your OpenStack account
        /// </summary>
        public readonly string User;

        [OutputConstructor]
        private ServiceComputeLoggingOpenstack(
            string accessKey,

            string bucketName,

            int? gzipLevel,

            string? messageType,

            string name,

            string? path,

            int? period,

            string? publicKey,

            string? timestampFormat,

            string url,

            string user)
        {
            AccessKey = accessKey;
            BucketName = bucketName;
            GzipLevel = gzipLevel;
            MessageType = messageType;
            Name = name;
            Path = path;
            Period = period;
            PublicKey = publicKey;
            TimestampFormat = timestampFormat;
            Url = url;
            User = user;
        }
    }
}
