// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fastly.Outputs
{

    [OutputType]
    public sealed class ServiceComputeLoggingGooglepubsub
    {
        /// <summary>
        /// The unique name of the Kinesis logging endpoint.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The ID of your Google Cloud Platform project.
        /// </summary>
        public readonly string ProjectId;
        /// <summary>
        /// The AWS secret access key to authenticate with.
        /// </summary>
        public readonly string SecretKey;
        /// <summary>
        /// The Kinesis stream name.
        /// </summary>
        public readonly string Topic;
        /// <summary>
        /// The username for your Cloud Files account.
        /// </summary>
        public readonly string User;

        [OutputConstructor]
        private ServiceComputeLoggingGooglepubsub(
            string name,

            string projectId,

            string secretKey,

            string topic,

            string user)
        {
            Name = name;
            ProjectId = projectId;
            SecretKey = secretKey;
            Topic = topic;
            User = user;
        }
    }
}
