// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.fastly.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetApiSecurityOperationsPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetApiSecurityOperationsPlainArgs Empty = new GetApiSecurityOperationsPlainArgs();

    /**
     * Filter by one or more domains (exact match).
     * 
     */
    @Import(name="domains")
    private @Nullable List<String> domains;

    /**
     * @return Filter by one or more domains (exact match).
     * 
     */
    public Optional<List<String>> domains() {
        return Optional.ofNullable(this.domains);
    }

    /**
     * Filter by one or more HTTP methods.
     * 
     */
    @Import(name="methods")
    private @Nullable List<String> methods;

    /**
     * @return Filter by one or more HTTP methods.
     * 
     */
    public Optional<List<String>> methods() {
        return Optional.ofNullable(this.methods);
    }

    /**
     * Filter by path (exact match).
     * 
     */
    @Import(name="path")
    private @Nullable String path;

    /**
     * @return Filter by path (exact match).
     * 
     */
    public Optional<String> path() {
        return Optional.ofNullable(this.path);
    }

    /**
     * Service ID.
     * 
     */
    @Import(name="serviceId", required=true)
    private String serviceId;

    /**
     * @return Service ID.
     * 
     */
    public String serviceId() {
        return this.serviceId;
    }

    /**
     * Filter by tag ID.
     * 
     */
    @Import(name="tagId")
    private @Nullable String tagId;

    /**
     * @return Filter by tag ID.
     * 
     */
    public Optional<String> tagId() {
        return Optional.ofNullable(this.tagId);
    }

    private GetApiSecurityOperationsPlainArgs() {}

    private GetApiSecurityOperationsPlainArgs(GetApiSecurityOperationsPlainArgs $) {
        this.domains = $.domains;
        this.methods = $.methods;
        this.path = $.path;
        this.serviceId = $.serviceId;
        this.tagId = $.tagId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetApiSecurityOperationsPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetApiSecurityOperationsPlainArgs $;

        public Builder() {
            $ = new GetApiSecurityOperationsPlainArgs();
        }

        public Builder(GetApiSecurityOperationsPlainArgs defaults) {
            $ = new GetApiSecurityOperationsPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param domains Filter by one or more domains (exact match).
         * 
         * @return builder
         * 
         */
        public Builder domains(@Nullable List<String> domains) {
            $.domains = domains;
            return this;
        }

        /**
         * @param domains Filter by one or more domains (exact match).
         * 
         * @return builder
         * 
         */
        public Builder domains(String... domains) {
            return domains(List.of(domains));
        }

        /**
         * @param methods Filter by one or more HTTP methods.
         * 
         * @return builder
         * 
         */
        public Builder methods(@Nullable List<String> methods) {
            $.methods = methods;
            return this;
        }

        /**
         * @param methods Filter by one or more HTTP methods.
         * 
         * @return builder
         * 
         */
        public Builder methods(String... methods) {
            return methods(List.of(methods));
        }

        /**
         * @param path Filter by path (exact match).
         * 
         * @return builder
         * 
         */
        public Builder path(@Nullable String path) {
            $.path = path;
            return this;
        }

        /**
         * @param serviceId Service ID.
         * 
         * @return builder
         * 
         */
        public Builder serviceId(String serviceId) {
            $.serviceId = serviceId;
            return this;
        }

        /**
         * @param tagId Filter by tag ID.
         * 
         * @return builder
         * 
         */
        public Builder tagId(@Nullable String tagId) {
            $.tagId = tagId;
            return this;
        }

        public GetApiSecurityOperationsPlainArgs build() {
            if ($.serviceId == null) {
                throw new MissingRequiredPropertyException("GetApiSecurityOperationsPlainArgs", "serviceId");
            }
            return $;
        }
    }

}
