// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.fastly.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.fastly.inputs.NgwafAccountRuleGroupConditionConditionArgs;
import com.pulumi.fastly.inputs.NgwafAccountRuleGroupConditionMultivalConditionArgs;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class NgwafAccountRuleGroupConditionArgs extends com.pulumi.resources.ResourceArgs {

    public static final NgwafAccountRuleGroupConditionArgs Empty = new NgwafAccountRuleGroupConditionArgs();

    /**
     * A list of nested conditions in this group.
     * 
     */
    @Import(name="conditions")
    private @Nullable Output<List<NgwafAccountRuleGroupConditionConditionArgs>> conditions;

    /**
     * @return A list of nested conditions in this group.
     * 
     */
    public Optional<Output<List<NgwafAccountRuleGroupConditionConditionArgs>>> conditions() {
        return Optional.ofNullable(this.conditions);
    }

    /**
     * Logical operator for the group. Accepted values are `any` and `all`.
     * 
     */
    @Import(name="groupOperator", required=true)
    private Output<String> groupOperator;

    /**
     * @return Logical operator for the group. Accepted values are `any` and `all`.
     * 
     */
    public Output<String> groupOperator() {
        return this.groupOperator;
    }

    /**
     * List of nested multival conditions in this group. Each multival list must define a `field, operator, groupOperator` and at least one condition.
     * 
     */
    @Import(name="multivalConditions")
    private @Nullable Output<List<NgwafAccountRuleGroupConditionMultivalConditionArgs>> multivalConditions;

    /**
     * @return List of nested multival conditions in this group. Each multival list must define a `field, operator, groupOperator` and at least one condition.
     * 
     */
    public Optional<Output<List<NgwafAccountRuleGroupConditionMultivalConditionArgs>>> multivalConditions() {
        return Optional.ofNullable(this.multivalConditions);
    }

    private NgwafAccountRuleGroupConditionArgs() {}

    private NgwafAccountRuleGroupConditionArgs(NgwafAccountRuleGroupConditionArgs $) {
        this.conditions = $.conditions;
        this.groupOperator = $.groupOperator;
        this.multivalConditions = $.multivalConditions;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NgwafAccountRuleGroupConditionArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NgwafAccountRuleGroupConditionArgs $;

        public Builder() {
            $ = new NgwafAccountRuleGroupConditionArgs();
        }

        public Builder(NgwafAccountRuleGroupConditionArgs defaults) {
            $ = new NgwafAccountRuleGroupConditionArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param conditions A list of nested conditions in this group.
         * 
         * @return builder
         * 
         */
        public Builder conditions(@Nullable Output<List<NgwafAccountRuleGroupConditionConditionArgs>> conditions) {
            $.conditions = conditions;
            return this;
        }

        /**
         * @param conditions A list of nested conditions in this group.
         * 
         * @return builder
         * 
         */
        public Builder conditions(List<NgwafAccountRuleGroupConditionConditionArgs> conditions) {
            return conditions(Output.of(conditions));
        }

        /**
         * @param conditions A list of nested conditions in this group.
         * 
         * @return builder
         * 
         */
        public Builder conditions(NgwafAccountRuleGroupConditionConditionArgs... conditions) {
            return conditions(List.of(conditions));
        }

        /**
         * @param groupOperator Logical operator for the group. Accepted values are `any` and `all`.
         * 
         * @return builder
         * 
         */
        public Builder groupOperator(Output<String> groupOperator) {
            $.groupOperator = groupOperator;
            return this;
        }

        /**
         * @param groupOperator Logical operator for the group. Accepted values are `any` and `all`.
         * 
         * @return builder
         * 
         */
        public Builder groupOperator(String groupOperator) {
            return groupOperator(Output.of(groupOperator));
        }

        /**
         * @param multivalConditions List of nested multival conditions in this group. Each multival list must define a `field, operator, groupOperator` and at least one condition.
         * 
         * @return builder
         * 
         */
        public Builder multivalConditions(@Nullable Output<List<NgwafAccountRuleGroupConditionMultivalConditionArgs>> multivalConditions) {
            $.multivalConditions = multivalConditions;
            return this;
        }

        /**
         * @param multivalConditions List of nested multival conditions in this group. Each multival list must define a `field, operator, groupOperator` and at least one condition.
         * 
         * @return builder
         * 
         */
        public Builder multivalConditions(List<NgwafAccountRuleGroupConditionMultivalConditionArgs> multivalConditions) {
            return multivalConditions(Output.of(multivalConditions));
        }

        /**
         * @param multivalConditions List of nested multival conditions in this group. Each multival list must define a `field, operator, groupOperator` and at least one condition.
         * 
         * @return builder
         * 
         */
        public Builder multivalConditions(NgwafAccountRuleGroupConditionMultivalConditionArgs... multivalConditions) {
            return multivalConditions(List.of(multivalConditions));
        }

        public NgwafAccountRuleGroupConditionArgs build() {
            if ($.groupOperator == null) {
                throw new MissingRequiredPropertyException("NgwafAccountRuleGroupConditionArgs", "groupOperator");
            }
            return $;
        }
    }

}
