// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.fastly.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class NgwafAlertMailingListIntegrationState extends com.pulumi.resources.ResourceArgs {

    public static final NgwafAlertMailingListIntegrationState Empty = new NgwafAlertMailingListIntegrationState();

    /**
     * Email address that the alert will use.
     * 
     */
    @Import(name="address")
    private @Nullable Output<String> address;

    /**
     * @return Email address that the alert will use.
     * 
     */
    public Optional<Output<String>> address() {
        return Optional.ofNullable(this.address);
    }

    /**
     * The description of the alert.
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return The description of the alert.
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * The ID of the workspace.
     * 
     */
    @Import(name="workspaceId")
    private @Nullable Output<String> workspaceId;

    /**
     * @return The ID of the workspace.
     * 
     */
    public Optional<Output<String>> workspaceId() {
        return Optional.ofNullable(this.workspaceId);
    }

    private NgwafAlertMailingListIntegrationState() {}

    private NgwafAlertMailingListIntegrationState(NgwafAlertMailingListIntegrationState $) {
        this.address = $.address;
        this.description = $.description;
        this.workspaceId = $.workspaceId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NgwafAlertMailingListIntegrationState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NgwafAlertMailingListIntegrationState $;

        public Builder() {
            $ = new NgwafAlertMailingListIntegrationState();
        }

        public Builder(NgwafAlertMailingListIntegrationState defaults) {
            $ = new NgwafAlertMailingListIntegrationState(Objects.requireNonNull(defaults));
        }

        /**
         * @param address Email address that the alert will use.
         * 
         * @return builder
         * 
         */
        public Builder address(@Nullable Output<String> address) {
            $.address = address;
            return this;
        }

        /**
         * @param address Email address that the alert will use.
         * 
         * @return builder
         * 
         */
        public Builder address(String address) {
            return address(Output.of(address));
        }

        /**
         * @param description The description of the alert.
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description The description of the alert.
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param workspaceId The ID of the workspace.
         * 
         * @return builder
         * 
         */
        public Builder workspaceId(@Nullable Output<String> workspaceId) {
            $.workspaceId = workspaceId;
            return this;
        }

        /**
         * @param workspaceId The ID of the workspace.
         * 
         * @return builder
         * 
         */
        public Builder workspaceId(String workspaceId) {
            return workspaceId(Output.of(workspaceId));
        }

        public NgwafAlertMailingListIntegrationState build() {
            return $;
        }
    }

}
