// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.fastly.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.fastly.inputs.NgwafWorkspaceAttackSignalThresholdsArgs;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class NgwafWorkspaceState extends com.pulumi.resources.ResourceArgs {

    public static final NgwafWorkspaceState Empty = new NgwafWorkspaceState();

    /**
     * Attack threshold parameters for system site alerts. Each threshold value is the number of attack signals per IP address that must be detected during the interval before the related IP address is flagged. If no values are set then the default value for each field will be applied
     * 
     */
    @Import(name="attackSignalThresholds")
    private @Nullable Output<NgwafWorkspaceAttackSignalThresholdsArgs> attackSignalThresholds;

    /**
     * @return Attack threshold parameters for system site alerts. Each threshold value is the number of attack signals per IP address that must be detected during the interval before the related IP address is flagged. If no values are set then the default value for each field will be applied
     * 
     */
    public Optional<Output<NgwafWorkspaceAttackSignalThresholdsArgs>> attackSignalThresholds() {
        return Optional.ofNullable(this.attackSignalThresholds);
    }

    /**
     * Specifies the request headers containing the client IP address. Maximum of 10 header names.
     * 
     */
    @Import(name="clientIpHeaders")
    private @Nullable Output<List<String>> clientIpHeaders;

    /**
     * @return Specifies the request headers containing the client IP address. Maximum of 10 header names.
     * 
     */
    public Optional<Output<List<String>>> clientIpHeaders() {
        return Optional.ofNullable(this.clientIpHeaders);
    }

    /**
     * The status code returned when a request is blocked. This configuration is applied at the workspace but can be overwritten in rules. Accepted values are [`301`, `302`, `400..599`]. Default value `406`.
     * 
     */
    @Import(name="defaultBlockingResponseCode")
    private @Nullable Output<Integer> defaultBlockingResponseCode;

    /**
     * @return The status code returned when a request is blocked. This configuration is applied at the workspace but can be overwritten in rules. Accepted values are [`301`, `302`, `400..599`]. Default value `406`.
     * 
     */
    public Optional<Output<Integer>> defaultBlockingResponseCode() {
        return Optional.ofNullable(this.defaultBlockingResponseCode);
    }

    /**
     * The description of the workspace
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return The description of the workspace
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * Agents will anonymize IP addresses according to the option selected. Accepted value is `hashed`.
     * 
     */
    @Import(name="ipAnonymization")
    private @Nullable Output<String> ipAnonymization;

    /**
     * @return Agents will anonymize IP addresses according to the option selected. Accepted value is `hashed`.
     * 
     */
    public Optional<Output<String>> ipAnonymization() {
        return Optional.ofNullable(this.ipAnonymization);
    }

    /**
     * The operation mode of the workspace. Accepted values are `off`, `block`, and `log`.
     * 
     */
    @Import(name="mode")
    private @Nullable Output<String> mode;

    /**
     * @return The operation mode of the workspace. Accepted values are `off`, `block`, and `log`.
     * 
     */
    public Optional<Output<String>> mode() {
        return Optional.ofNullable(this.mode);
    }

    /**
     * The display name of the workspace.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The display name of the workspace.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    private NgwafWorkspaceState() {}

    private NgwafWorkspaceState(NgwafWorkspaceState $) {
        this.attackSignalThresholds = $.attackSignalThresholds;
        this.clientIpHeaders = $.clientIpHeaders;
        this.defaultBlockingResponseCode = $.defaultBlockingResponseCode;
        this.description = $.description;
        this.ipAnonymization = $.ipAnonymization;
        this.mode = $.mode;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NgwafWorkspaceState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NgwafWorkspaceState $;

        public Builder() {
            $ = new NgwafWorkspaceState();
        }

        public Builder(NgwafWorkspaceState defaults) {
            $ = new NgwafWorkspaceState(Objects.requireNonNull(defaults));
        }

        /**
         * @param attackSignalThresholds Attack threshold parameters for system site alerts. Each threshold value is the number of attack signals per IP address that must be detected during the interval before the related IP address is flagged. If no values are set then the default value for each field will be applied
         * 
         * @return builder
         * 
         */
        public Builder attackSignalThresholds(@Nullable Output<NgwafWorkspaceAttackSignalThresholdsArgs> attackSignalThresholds) {
            $.attackSignalThresholds = attackSignalThresholds;
            return this;
        }

        /**
         * @param attackSignalThresholds Attack threshold parameters for system site alerts. Each threshold value is the number of attack signals per IP address that must be detected during the interval before the related IP address is flagged. If no values are set then the default value for each field will be applied
         * 
         * @return builder
         * 
         */
        public Builder attackSignalThresholds(NgwafWorkspaceAttackSignalThresholdsArgs attackSignalThresholds) {
            return attackSignalThresholds(Output.of(attackSignalThresholds));
        }

        /**
         * @param clientIpHeaders Specifies the request headers containing the client IP address. Maximum of 10 header names.
         * 
         * @return builder
         * 
         */
        public Builder clientIpHeaders(@Nullable Output<List<String>> clientIpHeaders) {
            $.clientIpHeaders = clientIpHeaders;
            return this;
        }

        /**
         * @param clientIpHeaders Specifies the request headers containing the client IP address. Maximum of 10 header names.
         * 
         * @return builder
         * 
         */
        public Builder clientIpHeaders(List<String> clientIpHeaders) {
            return clientIpHeaders(Output.of(clientIpHeaders));
        }

        /**
         * @param clientIpHeaders Specifies the request headers containing the client IP address. Maximum of 10 header names.
         * 
         * @return builder
         * 
         */
        public Builder clientIpHeaders(String... clientIpHeaders) {
            return clientIpHeaders(List.of(clientIpHeaders));
        }

        /**
         * @param defaultBlockingResponseCode The status code returned when a request is blocked. This configuration is applied at the workspace but can be overwritten in rules. Accepted values are [`301`, `302`, `400..599`]. Default value `406`.
         * 
         * @return builder
         * 
         */
        public Builder defaultBlockingResponseCode(@Nullable Output<Integer> defaultBlockingResponseCode) {
            $.defaultBlockingResponseCode = defaultBlockingResponseCode;
            return this;
        }

        /**
         * @param defaultBlockingResponseCode The status code returned when a request is blocked. This configuration is applied at the workspace but can be overwritten in rules. Accepted values are [`301`, `302`, `400..599`]. Default value `406`.
         * 
         * @return builder
         * 
         */
        public Builder defaultBlockingResponseCode(Integer defaultBlockingResponseCode) {
            return defaultBlockingResponseCode(Output.of(defaultBlockingResponseCode));
        }

        /**
         * @param description The description of the workspace
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description The description of the workspace
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param ipAnonymization Agents will anonymize IP addresses according to the option selected. Accepted value is `hashed`.
         * 
         * @return builder
         * 
         */
        public Builder ipAnonymization(@Nullable Output<String> ipAnonymization) {
            $.ipAnonymization = ipAnonymization;
            return this;
        }

        /**
         * @param ipAnonymization Agents will anonymize IP addresses according to the option selected. Accepted value is `hashed`.
         * 
         * @return builder
         * 
         */
        public Builder ipAnonymization(String ipAnonymization) {
            return ipAnonymization(Output.of(ipAnonymization));
        }

        /**
         * @param mode The operation mode of the workspace. Accepted values are `off`, `block`, and `log`.
         * 
         * @return builder
         * 
         */
        public Builder mode(@Nullable Output<String> mode) {
            $.mode = mode;
            return this;
        }

        /**
         * @param mode The operation mode of the workspace. Accepted values are `off`, `block`, and `log`.
         * 
         * @return builder
         * 
         */
        public Builder mode(String mode) {
            return mode(Output.of(mode));
        }

        /**
         * @param name The display name of the workspace.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The display name of the workspace.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        public NgwafWorkspaceState build() {
            return $;
        }
    }

}
