// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.fastly.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ServiceVclAclArgs extends com.pulumi.resources.ResourceArgs {

    public static final ServiceVclAclArgs Empty = new ServiceVclAclArgs();

    /**
     * The ID of the ACL
     * 
     */
    @Import(name="aclId")
    private @Nullable Output<String> aclId;

    /**
     * @return The ID of the ACL
     * 
     */
    public Optional<Output<String>> aclId() {
        return Optional.ofNullable(this.aclId);
    }

    /**
     * Allow the ACL to be deleted, even if it contains entries. Defaults to false.
     * 
     */
    @Import(name="forceDestroy")
    private @Nullable Output<Boolean> forceDestroy;

    /**
     * @return Allow the ACL to be deleted, even if it contains entries. Defaults to false.
     * 
     */
    public Optional<Output<Boolean>> forceDestroy() {
        return Optional.ofNullable(this.forceDestroy);
    }

    /**
     * A unique name to identify this ACL. It is important to note that changing this attribute will delete and recreate the ACL, and discard the current items in the ACL
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return A unique name to identify this ACL. It is important to note that changing this attribute will delete and recreate the ACL, and discard the current items in the ACL
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    private ServiceVclAclArgs() {}

    private ServiceVclAclArgs(ServiceVclAclArgs $) {
        this.aclId = $.aclId;
        this.forceDestroy = $.forceDestroy;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ServiceVclAclArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ServiceVclAclArgs $;

        public Builder() {
            $ = new ServiceVclAclArgs();
        }

        public Builder(ServiceVclAclArgs defaults) {
            $ = new ServiceVclAclArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param aclId The ID of the ACL
         * 
         * @return builder
         * 
         */
        public Builder aclId(@Nullable Output<String> aclId) {
            $.aclId = aclId;
            return this;
        }

        /**
         * @param aclId The ID of the ACL
         * 
         * @return builder
         * 
         */
        public Builder aclId(String aclId) {
            return aclId(Output.of(aclId));
        }

        /**
         * @param forceDestroy Allow the ACL to be deleted, even if it contains entries. Defaults to false.
         * 
         * @return builder
         * 
         */
        public Builder forceDestroy(@Nullable Output<Boolean> forceDestroy) {
            $.forceDestroy = forceDestroy;
            return this;
        }

        /**
         * @param forceDestroy Allow the ACL to be deleted, even if it contains entries. Defaults to false.
         * 
         * @return builder
         * 
         */
        public Builder forceDestroy(Boolean forceDestroy) {
            return forceDestroy(Output.of(forceDestroy));
        }

        /**
         * @param name A unique name to identify this ACL. It is important to note that changing this attribute will delete and recreate the ACL, and discard the current items in the ACL
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name A unique name to identify this ACL. It is important to note that changing this attribute will delete and recreate the ACL, and discard the current items in the ACL
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        public ServiceVclAclArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("ServiceVclAclArgs", "name");
            }
            return $;
        }
    }

}
