// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.fastly;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.fastly.inputs.AlertDimensionsArgs;
import com.pulumi.fastly.inputs.AlertEvaluationStrategyArgs;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class AlertArgs extends com.pulumi.resources.ResourceArgs {

    public static final AlertArgs Empty = new AlertArgs();

    /**
     * Additional text that is included in the alert notification.
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return Additional text that is included in the alert notification.
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * More filters depending on the source type.
     * 
     */
    @Import(name="dimensions")
    private @Nullable Output<AlertDimensionsArgs> dimensions;

    /**
     * @return More filters depending on the source type.
     * 
     */
    public Optional<Output<AlertDimensionsArgs>> dimensions() {
        return Optional.ofNullable(this.dimensions);
    }

    /**
     * Criteria on how to alert.
     * 
     */
    @Import(name="evaluationStrategy", required=true)
    private Output<AlertEvaluationStrategyArgs> evaluationStrategy;

    /**
     * @return Criteria on how to alert.
     * 
     */
    public Output<AlertEvaluationStrategyArgs> evaluationStrategy() {
        return this.evaluationStrategy;
    }

    /**
     * List of integrations used to notify when alert fires.
     * 
     */
    @Import(name="integrationIds")
    private @Nullable Output<List<String>> integrationIds;

    /**
     * @return List of integrations used to notify when alert fires.
     * 
     */
    public Optional<Output<List<String>>> integrationIds() {
        return Optional.ofNullable(this.integrationIds);
    }

    /**
     * The metric name to alert on for a specific source: [domains](https://developer.fastly.com/reference/api/metrics-stats/domain-inspector/historical), [origins](https://developer.fastly.com/reference/api/metrics-stats/origin-inspector/historical), or [stats](https://developer.fastly.com/reference/api/metrics-stats/historical-stats).
     * 
     */
    @Import(name="metric", required=true)
    private Output<String> metric;

    /**
     * @return The metric name to alert on for a specific source: [domains](https://developer.fastly.com/reference/api/metrics-stats/domain-inspector/historical), [origins](https://developer.fastly.com/reference/api/metrics-stats/origin-inspector/historical), or [stats](https://developer.fastly.com/reference/api/metrics-stats/historical-stats).
     * 
     */
    public Output<String> metric() {
        return this.metric;
    }

    /**
     * The name of the alert.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the alert.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The service which the alert monitors. Optional when using `stats` as the `source`.
     * 
     */
    @Import(name="serviceId")
    private @Nullable Output<String> serviceId;

    /**
     * @return The service which the alert monitors. Optional when using `stats` as the `source`.
     * 
     */
    public Optional<Output<String>> serviceId() {
        return Optional.ofNullable(this.serviceId);
    }

    /**
     * The source where the metric comes from. One of: `domains`, `origins`, `stats`.
     * 
     */
    @Import(name="source", required=true)
    private Output<String> source;

    /**
     * @return The source where the metric comes from. One of: `domains`, `origins`, `stats`.
     * 
     */
    public Output<String> source() {
        return this.source;
    }

    private AlertArgs() {}

    private AlertArgs(AlertArgs $) {
        this.description = $.description;
        this.dimensions = $.dimensions;
        this.evaluationStrategy = $.evaluationStrategy;
        this.integrationIds = $.integrationIds;
        this.metric = $.metric;
        this.name = $.name;
        this.serviceId = $.serviceId;
        this.source = $.source;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AlertArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AlertArgs $;

        public Builder() {
            $ = new AlertArgs();
        }

        public Builder(AlertArgs defaults) {
            $ = new AlertArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param description Additional text that is included in the alert notification.
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description Additional text that is included in the alert notification.
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param dimensions More filters depending on the source type.
         * 
         * @return builder
         * 
         */
        public Builder dimensions(@Nullable Output<AlertDimensionsArgs> dimensions) {
            $.dimensions = dimensions;
            return this;
        }

        /**
         * @param dimensions More filters depending on the source type.
         * 
         * @return builder
         * 
         */
        public Builder dimensions(AlertDimensionsArgs dimensions) {
            return dimensions(Output.of(dimensions));
        }

        /**
         * @param evaluationStrategy Criteria on how to alert.
         * 
         * @return builder
         * 
         */
        public Builder evaluationStrategy(Output<AlertEvaluationStrategyArgs> evaluationStrategy) {
            $.evaluationStrategy = evaluationStrategy;
            return this;
        }

        /**
         * @param evaluationStrategy Criteria on how to alert.
         * 
         * @return builder
         * 
         */
        public Builder evaluationStrategy(AlertEvaluationStrategyArgs evaluationStrategy) {
            return evaluationStrategy(Output.of(evaluationStrategy));
        }

        /**
         * @param integrationIds List of integrations used to notify when alert fires.
         * 
         * @return builder
         * 
         */
        public Builder integrationIds(@Nullable Output<List<String>> integrationIds) {
            $.integrationIds = integrationIds;
            return this;
        }

        /**
         * @param integrationIds List of integrations used to notify when alert fires.
         * 
         * @return builder
         * 
         */
        public Builder integrationIds(List<String> integrationIds) {
            return integrationIds(Output.of(integrationIds));
        }

        /**
         * @param integrationIds List of integrations used to notify when alert fires.
         * 
         * @return builder
         * 
         */
        public Builder integrationIds(String... integrationIds) {
            return integrationIds(List.of(integrationIds));
        }

        /**
         * @param metric The metric name to alert on for a specific source: [domains](https://developer.fastly.com/reference/api/metrics-stats/domain-inspector/historical), [origins](https://developer.fastly.com/reference/api/metrics-stats/origin-inspector/historical), or [stats](https://developer.fastly.com/reference/api/metrics-stats/historical-stats).
         * 
         * @return builder
         * 
         */
        public Builder metric(Output<String> metric) {
            $.metric = metric;
            return this;
        }

        /**
         * @param metric The metric name to alert on for a specific source: [domains](https://developer.fastly.com/reference/api/metrics-stats/domain-inspector/historical), [origins](https://developer.fastly.com/reference/api/metrics-stats/origin-inspector/historical), or [stats](https://developer.fastly.com/reference/api/metrics-stats/historical-stats).
         * 
         * @return builder
         * 
         */
        public Builder metric(String metric) {
            return metric(Output.of(metric));
        }

        /**
         * @param name The name of the alert.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the alert.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param serviceId The service which the alert monitors. Optional when using `stats` as the `source`.
         * 
         * @return builder
         * 
         */
        public Builder serviceId(@Nullable Output<String> serviceId) {
            $.serviceId = serviceId;
            return this;
        }

        /**
         * @param serviceId The service which the alert monitors. Optional when using `stats` as the `source`.
         * 
         * @return builder
         * 
         */
        public Builder serviceId(String serviceId) {
            return serviceId(Output.of(serviceId));
        }

        /**
         * @param source The source where the metric comes from. One of: `domains`, `origins`, `stats`.
         * 
         * @return builder
         * 
         */
        public Builder source(Output<String> source) {
            $.source = source;
            return this;
        }

        /**
         * @param source The source where the metric comes from. One of: `domains`, `origins`, `stats`.
         * 
         * @return builder
         * 
         */
        public Builder source(String source) {
            return source(Output.of(source));
        }

        public AlertArgs build() {
            if ($.evaluationStrategy == null) {
                throw new MissingRequiredPropertyException("AlertArgs", "evaluationStrategy");
            }
            if ($.metric == null) {
                throw new MissingRequiredPropertyException("AlertArgs", "metric");
            }
            if ($.source == null) {
                throw new MissingRequiredPropertyException("AlertArgs", "source");
            }
            return $;
        }
    }

}
