# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetComputeAclsResult',
    'AwaitableGetComputeAclsResult',
    'get_compute_acls',
    'get_compute_acls_output',
]

@pulumi.output_type
class GetComputeAclsResult:
    """
    A collection of values returned by getComputeAcls.
    """
    def __init__(__self__, acls=None, id=None):
        if acls and not isinstance(acls, list):
            raise TypeError("Expected argument 'acls' to be a list")
        pulumi.set(__self__, "acls", acls)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)

    @_builtins.property
    @pulumi.getter
    def acls(self) -> Sequence['outputs.GetComputeAclsAclResult']:
        """
        List of all Compute ACLs.
        """
        return pulumi.get(self, "acls")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")


class AwaitableGetComputeAclsResult(GetComputeAclsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetComputeAclsResult(
            acls=self.acls,
            id=self.id)


def get_compute_acls(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetComputeAclsResult:
    """
    Use this data source to retrieve a list of [Fastly Compute ACLs](https://www.fastly.com/documentation/reference/api/compute-acls/).
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('fastly:index/getComputeAcls:getComputeAcls', __args__, opts=opts, typ=GetComputeAclsResult).value

    return AwaitableGetComputeAclsResult(
        acls=pulumi.get(__ret__, 'acls'),
        id=pulumi.get(__ret__, 'id'))
def get_compute_acls_output(opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetComputeAclsResult]:
    """
    Use this data source to retrieve a list of [Fastly Compute ACLs](https://www.fastly.com/documentation/reference/api/compute-acls/).
    """
    __args__ = dict()
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('fastly:index/getComputeAcls:getComputeAcls', __args__, opts=opts, typ=GetComputeAclsResult)
    return __ret__.apply(lambda __response__: GetComputeAclsResult(
        acls=pulumi.get(__response__, 'acls'),
        id=pulumi.get(__response__, 'id')))
