# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetNgwafAlertMicrosoftTeamsIntegrationResult',
    'AwaitableGetNgwafAlertMicrosoftTeamsIntegrationResult',
    'get_ngwaf_alert_microsoft_teams_integration',
    'get_ngwaf_alert_microsoft_teams_integration_output',
]

@pulumi.output_type
class GetNgwafAlertMicrosoftTeamsIntegrationResult:
    """
    A collection of values returned by getNgwafAlertMicrosoftTeamsIntegration.
    """
    def __init__(__self__, id=None, microsoft_teams_alerts=None, workspace_id=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if microsoft_teams_alerts and not isinstance(microsoft_teams_alerts, list):
            raise TypeError("Expected argument 'microsoft_teams_alerts' to be a list")
        pulumi.set(__self__, "microsoft_teams_alerts", microsoft_teams_alerts)
        if workspace_id and not isinstance(workspace_id, str):
            raise TypeError("Expected argument 'workspace_id' to be a str")
        pulumi.set(__self__, "workspace_id", workspace_id)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="microsoftTeamsAlerts")
    def microsoft_teams_alerts(self) -> Sequence['outputs.GetNgwafAlertMicrosoftTeamsIntegrationMicrosoftTeamsAlertResult']:
        """
        List of all Microsoft Teams alerts for a workspace.
        """
        return pulumi.get(self, "microsoft_teams_alerts")

    @_builtins.property
    @pulumi.getter(name="workspaceId")
    def workspace_id(self) -> _builtins.str:
        """
        The ID of the workspace.
        """
        return pulumi.get(self, "workspace_id")


class AwaitableGetNgwafAlertMicrosoftTeamsIntegrationResult(GetNgwafAlertMicrosoftTeamsIntegrationResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetNgwafAlertMicrosoftTeamsIntegrationResult(
            id=self.id,
            microsoft_teams_alerts=self.microsoft_teams_alerts,
            workspace_id=self.workspace_id)


def get_ngwaf_alert_microsoft_teams_integration(workspace_id: Optional[_builtins.str] = None,
                                                opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetNgwafAlertMicrosoftTeamsIntegrationResult:
    """
    Use this data source to get a Fastly Next-Gen WAF Alert Microsoft Teams integration.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_fastly as fastly

    ngwaf_jira_alerts = fastly.get_ngwaf_alert_jira_integration(workspace_id=test_redactions_workspace["id"])
    pulumi.export("ngwafJiraAlertsAll", jira_alerts)
    ```


    :param _builtins.str workspace_id: The ID of the workspace.
    """
    __args__ = dict()
    __args__['workspaceId'] = workspace_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('fastly:index/getNgwafAlertMicrosoftTeamsIntegration:getNgwafAlertMicrosoftTeamsIntegration', __args__, opts=opts, typ=GetNgwafAlertMicrosoftTeamsIntegrationResult).value

    return AwaitableGetNgwafAlertMicrosoftTeamsIntegrationResult(
        id=pulumi.get(__ret__, 'id'),
        microsoft_teams_alerts=pulumi.get(__ret__, 'microsoft_teams_alerts'),
        workspace_id=pulumi.get(__ret__, 'workspace_id'))
def get_ngwaf_alert_microsoft_teams_integration_output(workspace_id: Optional[pulumi.Input[_builtins.str]] = None,
                                                       opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetNgwafAlertMicrosoftTeamsIntegrationResult]:
    """
    Use this data source to get a Fastly Next-Gen WAF Alert Microsoft Teams integration.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_fastly as fastly

    ngwaf_jira_alerts = fastly.get_ngwaf_alert_jira_integration(workspace_id=test_redactions_workspace["id"])
    pulumi.export("ngwafJiraAlertsAll", jira_alerts)
    ```


    :param _builtins.str workspace_id: The ID of the workspace.
    """
    __args__ = dict()
    __args__['workspaceId'] = workspace_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('fastly:index/getNgwafAlertMicrosoftTeamsIntegration:getNgwafAlertMicrosoftTeamsIntegration', __args__, opts=opts, typ=GetNgwafAlertMicrosoftTeamsIntegrationResult)
    return __ret__.apply(lambda __response__: GetNgwafAlertMicrosoftTeamsIntegrationResult(
        id=pulumi.get(__response__, 'id'),
        microsoft_teams_alerts=pulumi.get(__response__, 'microsoft_teams_alerts'),
        workspace_id=pulumi.get(__response__, 'workspace_id')))
