// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fastly.Inputs
{

    public sealed class NgwafWorkspaceRuleGroupConditionGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("conditions")]
        private InputList<Inputs.NgwafWorkspaceRuleGroupConditionConditionGetArgs>? _conditions;

        /// <summary>
        /// A list of nested conditions in this group.
        /// </summary>
        public InputList<Inputs.NgwafWorkspaceRuleGroupConditionConditionGetArgs> Conditions
        {
            get => _conditions ?? (_conditions = new InputList<Inputs.NgwafWorkspaceRuleGroupConditionConditionGetArgs>());
            set => _conditions = value;
        }

        /// <summary>
        /// Logical operator for the group. Accepted values are `Any` and `All`.
        /// </summary>
        [Input("groupOperator", required: true)]
        public Input<string> GroupOperator { get; set; } = null!;

        [Input("multivalConditions")]
        private InputList<Inputs.NgwafWorkspaceRuleGroupConditionMultivalConditionGetArgs>? _multivalConditions;

        /// <summary>
        /// List of nested multival conditions in this group. Each multival list must define a `field, operator, GroupOperator` and at least one condition.
        /// </summary>
        public InputList<Inputs.NgwafWorkspaceRuleGroupConditionMultivalConditionGetArgs> MultivalConditions
        {
            get => _multivalConditions ?? (_multivalConditions = new InputList<Inputs.NgwafWorkspaceRuleGroupConditionMultivalConditionGetArgs>());
            set => _multivalConditions = value;
        }

        public NgwafWorkspaceRuleGroupConditionGetArgs()
        {
        }
        public static new NgwafWorkspaceRuleGroupConditionGetArgs Empty => new NgwafWorkspaceRuleGroupConditionGetArgs();
    }
}
