// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fastly.Inputs
{

    public sealed class ServiceComputeLoggingDatadogArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The unique name of the Datadog logging endpoint. It is important to note that changing this attribute will delete and recreate the resource
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// The region that log data will be sent to. One of `US` or `EU`. Defaults to `US` if undefined
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        [Input("token", required: true)]
        private Input<string>? _token;

        /// <summary>
        /// The API key from your Datadog account
        /// </summary>
        public Input<string>? Token
        {
            get => _token;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _token = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public ServiceComputeLoggingDatadogArgs()
        {
        }
        public static new ServiceComputeLoggingDatadogArgs Empty => new ServiceComputeLoggingDatadogArgs();
    }
}
