// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fastly.Inputs
{

    public sealed class ServiceWafConfigurationRuleArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The Web Application Firewall rule's modsecurity ID
        /// </summary>
        [Input("modsecRuleId", required: true)]
        public Input<int> ModsecRuleId { get; set; } = null!;

        /// <summary>
        /// The Web Application Firewall rule's revision. The latest revision will be used if this is not provided
        /// </summary>
        [Input("revision")]
        public Input<int>? Revision { get; set; }

        /// <summary>
        /// The Web Application Firewall rule's status. Allowed values are (`log`, `block` and `score`)
        /// </summary>
        [Input("status", required: true)]
        public Input<string> Status { get; set; } = null!;

        public ServiceWafConfigurationRuleArgs()
        {
        }
    }
}
