// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fastly.Inputs
{

    public sealed class ServiceVclProductEnablementDdosProtectionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Enable DDoS Protection support
        /// </summary>
        [Input("enabled", required: true)]
        public Input<bool> Enabled { get; set; } = null!;

        /// <summary>
        /// Operation mode. Can be either `Off`, `Log`, or `Block`.
        /// </summary>
        [Input("mode", required: true)]
        public Input<string> Mode { get; set; } = null!;

        public ServiceVclProductEnablementDdosProtectionArgs()
        {
        }
        public static new ServiceVclProductEnablementDdosProtectionArgs Empty => new ServiceVclProductEnablementDdosProtectionArgs();
    }
}
