// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages an API Security operation for a Fastly service. Operations represent API endpoints (method + domain + path) and can optionally be associated with operation tags.
 *
 * ## Example Usage
 *
 * Basic usage:
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as fastly from "@pulumi/fastly";
 *
 * const svc1 = new fastly.ServiceVcl("svc1", {
 *     name: "test-svc-1-example",
 *     forceDestroy: true,
 *     backends: [{
 *         address: "example.com",
 *         name: "tf-test-backend-1",
 *     }],
 * });
 * const example = new fastly.ApiSecurityOperation("example", {
 *     serviceId: svc1.id,
 *     method: "GET",
 *     domain: "api.example.com",
 *     path: "/v1/things",
 *     description: "Retrieve things",
 * });
 * ```
 *
 * With tags:
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as fastly from "@pulumi/fastly";
 *
 * const svc1 = new fastly.ServiceVcl("svc1", {
 *     name: "test-svc-1-example",
 *     forceDestroy: true,
 *     backends: [{
 *         address: "example.com",
 *         name: "tf-test-backend-1",
 *     }],
 * });
 * const tag = new fastly.ApiSecurityOperationTag("tag", {
 *     serviceId: svc1.id,
 *     name: "production",
 *     description: "Production endpoints",
 * });
 * const example = new fastly.ApiSecurityOperation("example", {
 *     serviceId: svc1.id,
 *     method: "GET",
 *     domain: "api.example.com",
 *     path: "/v1/things",
 *     description: "Retrieve things",
 *     tagIds: [tag.tagId],
 * });
 * ```
 *
 * ## Import
 *
 * API Security operations can be imported using a composite ID of the form `<service_id>/<operation_id>`, e.g.
 *
 * ```sh
 * $ pulumi import fastly:index/apiSecurityOperation:ApiSecurityOperation example <service_id>/<operation_id>
 * ```
 */
export class ApiSecurityOperation extends pulumi.CustomResource {
    /**
     * Get an existing ApiSecurityOperation resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ApiSecurityOperationState, opts?: pulumi.CustomResourceOptions): ApiSecurityOperation {
        return new ApiSecurityOperation(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'fastly:index/apiSecurityOperation:ApiSecurityOperation';

    /**
     * Returns true if the given object is an instance of ApiSecurityOperation.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ApiSecurityOperation {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ApiSecurityOperation.__pulumiType;
    }

    /**
     * Created timestamp (when present).
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * A description of the operation.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Domain for the operation (exact match). Can be created, but not updated.
     */
    declare public readonly domain: pulumi.Output<string>;
    /**
     * Last seen timestamp (when present).
     */
    declare public /*out*/ readonly lastSeenAt: pulumi.Output<string>;
    /**
     * HTTP method for the operation (e.g. GET, POST). Can be created, but not updated.
     */
    declare public readonly method: pulumi.Output<string>;
    /**
     * The operation ID.
     */
    declare public /*out*/ readonly operationId: pulumi.Output<string>;
    /**
     * Path for the operation (exact match). Can be created, but not updated.
     */
    declare public readonly path: pulumi.Output<string>;
    /**
     * Observed requests per second (when present).
     */
    declare public /*out*/ readonly rps: pulumi.Output<number>;
    /**
     * Service ID the operation belongs to. To import, use: \n\n/\n\n.
     */
    declare public readonly serviceId: pulumi.Output<string>;
    /**
     * Discovery status (when present).
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    /**
     * Associated operation tag IDs.
     */
    declare public readonly tagIds: pulumi.Output<string[] | undefined>;
    /**
     * Updated timestamp (when present).
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;

    /**
     * Create a ApiSecurityOperation resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ApiSecurityOperationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ApiSecurityOperationArgs | ApiSecurityOperationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ApiSecurityOperationState | undefined;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["description"] = state?.description;
            resourceInputs["domain"] = state?.domain;
            resourceInputs["lastSeenAt"] = state?.lastSeenAt;
            resourceInputs["method"] = state?.method;
            resourceInputs["operationId"] = state?.operationId;
            resourceInputs["path"] = state?.path;
            resourceInputs["rps"] = state?.rps;
            resourceInputs["serviceId"] = state?.serviceId;
            resourceInputs["status"] = state?.status;
            resourceInputs["tagIds"] = state?.tagIds;
            resourceInputs["updatedAt"] = state?.updatedAt;
        } else {
            const args = argsOrState as ApiSecurityOperationArgs | undefined;
            if (args?.domain === undefined && !opts.urn) {
                throw new Error("Missing required property 'domain'");
            }
            if (args?.method === undefined && !opts.urn) {
                throw new Error("Missing required property 'method'");
            }
            if (args?.path === undefined && !opts.urn) {
                throw new Error("Missing required property 'path'");
            }
            if (args?.serviceId === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceId'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["domain"] = args?.domain;
            resourceInputs["method"] = args?.method;
            resourceInputs["path"] = args?.path;
            resourceInputs["serviceId"] = args?.serviceId;
            resourceInputs["tagIds"] = args?.tagIds;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["lastSeenAt"] = undefined /*out*/;
            resourceInputs["operationId"] = undefined /*out*/;
            resourceInputs["rps"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ApiSecurityOperation.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ApiSecurityOperation resources.
 */
export interface ApiSecurityOperationState {
    /**
     * Created timestamp (when present).
     */
    createdAt?: pulumi.Input<string>;
    /**
     * A description of the operation.
     */
    description?: pulumi.Input<string>;
    /**
     * Domain for the operation (exact match). Can be created, but not updated.
     */
    domain?: pulumi.Input<string>;
    /**
     * Last seen timestamp (when present).
     */
    lastSeenAt?: pulumi.Input<string>;
    /**
     * HTTP method for the operation (e.g. GET, POST). Can be created, but not updated.
     */
    method?: pulumi.Input<string>;
    /**
     * The operation ID.
     */
    operationId?: pulumi.Input<string>;
    /**
     * Path for the operation (exact match). Can be created, but not updated.
     */
    path?: pulumi.Input<string>;
    /**
     * Observed requests per second (when present).
     */
    rps?: pulumi.Input<number>;
    /**
     * Service ID the operation belongs to. To import, use: \n\n/\n\n.
     */
    serviceId?: pulumi.Input<string>;
    /**
     * Discovery status (when present).
     */
    status?: pulumi.Input<string>;
    /**
     * Associated operation tag IDs.
     */
    tagIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Updated timestamp (when present).
     */
    updatedAt?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ApiSecurityOperation resource.
 */
export interface ApiSecurityOperationArgs {
    /**
     * A description of the operation.
     */
    description?: pulumi.Input<string>;
    /**
     * Domain for the operation (exact match). Can be created, but not updated.
     */
    domain: pulumi.Input<string>;
    /**
     * HTTP method for the operation (e.g. GET, POST). Can be created, but not updated.
     */
    method: pulumi.Input<string>;
    /**
     * Path for the operation (exact match). Can be created, but not updated.
     */
    path: pulumi.Input<string>;
    /**
     * Service ID the operation belongs to. To import, use: \n\n/\n\n.
     */
    serviceId: pulumi.Input<string>;
    /**
     * Associated operation tag IDs.
     */
    tagIds?: pulumi.Input<pulumi.Input<string>[]>;
}
