// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Use this data source to get the [IP ranges](https://docs.fastly.com/guides/securing-communications/accessing-fastlys-ip-ranges) of Fastly edge nodes.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 * import * as fastly from "@pulumi/fastly";
 *
 * const fastly = fastly.getFastlyIpRanges({});
 * const fromFastly = new aws.ec2.SecurityGroup("from_fastly", {
 *     name: "from_fastly",
 *     ingress: [{
 *         fromPort: 443,
 *         toPort: 443,
 *         protocol: "tcp",
 *         cidrBlocks: fastly.then(fastly => fastly.cidrBlocks),
 *         ipv6CidrBlocks: fastly.then(fastly => fastly.ipv6CidrBlocks),
 *     }],
 * });
 * ```
 *
 * [1]: https://docs.fastly.com/guides/securing-communications/accessing-fastlys-ip-ranges
 */
export function getFastlyIpRanges(opts?: pulumi.InvokeOptions): Promise<GetFastlyIpRangesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("fastly:index/getFastlyIpRanges:getFastlyIpRanges", {
    }, opts);
}

/**
 * A collection of values returned by getFastlyIpRanges.
 */
export interface GetFastlyIpRangesResult {
    /**
     * The lexically ordered list of ipv4 CIDR blocks.
     */
    readonly cidrBlocks: string[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The lexically ordered list of ipv6 CIDR blocks.
     */
    readonly ipv6CidrBlocks: string[];
}
/**
 * Use this data source to get the [IP ranges](https://docs.fastly.com/guides/securing-communications/accessing-fastlys-ip-ranges) of Fastly edge nodes.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 * import * as fastly from "@pulumi/fastly";
 *
 * const fastly = fastly.getFastlyIpRanges({});
 * const fromFastly = new aws.ec2.SecurityGroup("from_fastly", {
 *     name: "from_fastly",
 *     ingress: [{
 *         fromPort: 443,
 *         toPort: 443,
 *         protocol: "tcp",
 *         cidrBlocks: fastly.then(fastly => fastly.cidrBlocks),
 *         ipv6CidrBlocks: fastly.then(fastly => fastly.ipv6CidrBlocks),
 *     }],
 * });
 * ```
 *
 * [1]: https://docs.fastly.com/guides/securing-communications/accessing-fastlys-ip-ranges
 */
export function getFastlyIpRangesOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetFastlyIpRangesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("fastly:index/getFastlyIpRanges:getFastlyIpRanges", {
    }, opts);
}
