// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * layout: "fastly"
 * page_title: "Fastly: fastly.getTlsConfigurationIds"
 * sidebar_current: "docs-fastly-datasource-tls_configuration_ids"
 * description: |-
 * Get IDs of available TLS Configurations.
 * <!-- yaml: line 6: could not find expected ':' -->
 *
 * # fastly.getTlsConfigurationIds
 *
 * Use this data source to get the IDs of available TLS configurations for use with other resources.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as fastly from "@pulumi/fastly";
 *
 * const example = fastly.getTlsConfigurationIds({});
 * const exampleTlsActivation = new fastly.TlsActivation("example", {configurationId: example.then(example => example.ids?.[0])});
 * ```
 */
export function getTlsConfigurationIds(opts?: pulumi.InvokeOptions): Promise<GetTlsConfigurationIdsResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("fastly:index/getTlsConfigurationIds:getTlsConfigurationIds", {
    }, opts);
}

/**
 * A collection of values returned by getTlsConfigurationIds.
 */
export interface GetTlsConfigurationIdsResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * List of IDs corresponding to available TLS configurations.
     */
    readonly ids: string[];
}
/**
 * layout: "fastly"
 * page_title: "Fastly: fastly.getTlsConfigurationIds"
 * sidebar_current: "docs-fastly-datasource-tls_configuration_ids"
 * description: |-
 * Get IDs of available TLS Configurations.
 * <!-- yaml: line 6: could not find expected ':' -->
 *
 * # fastly.getTlsConfigurationIds
 *
 * Use this data source to get the IDs of available TLS configurations for use with other resources.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as fastly from "@pulumi/fastly";
 *
 * const example = fastly.getTlsConfigurationIds({});
 * const exampleTlsActivation = new fastly.TlsActivation("example", {configurationId: example.then(example => example.ids?.[0])});
 * ```
 */
export function getTlsConfigurationIdsOutput(opts?: pulumi.InvokeOptions): pulumi.Output<GetTlsConfigurationIdsResult> {
    return pulumi.output(getTlsConfigurationIds(opts))
}
