// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export * from "./getDatacenters";
export * from "./getFastlyIpRanges";
export * from "./getServices";
export * from "./getTlsActivation";
export * from "./getTlsActivationIds";
export * from "./getTlsCertificate";
export * from "./getTlsCertificateIds";
export * from "./getTlsConfiguration";
export * from "./getTlsConfigurationIds";
export * from "./getTlsDomain";
export * from "./getTlsPlatformCertificate";
export * from "./getTlsPlatformCertificateIds";
export * from "./getTlsPrivateKey";
export * from "./getTlsPrivateKeyIds";
export * from "./getTlsSubscription";
export * from "./getTlsSubscriptionIds";
export * from "./getWafRules";
export * from "./provider";
export * from "./serviceACLEntries";
export * from "./serviceAuthorization";
export * from "./serviceCompute";
export * from "./serviceDictionaryItems";
export * from "./serviceDynamicSnippetContent";
export * from "./serviceVcl";
export * from "./serviceWafConfiguration";
export * from "./tlsActivation";
export * from "./tlsCertificate";
export * from "./tlsPlatformCertificate";
export * from "./tlsPrivateKey";
export * from "./tlsSubscription";
export * from "./tlsSubscriptionValidation";
export * from "./user";

// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

// Import resources to register:
import { ServiceACLEntries } from "./serviceACLEntries";
import { ServiceAuthorization } from "./serviceAuthorization";
import { ServiceCompute } from "./serviceCompute";
import { ServiceDictionaryItems } from "./serviceDictionaryItems";
import { ServiceDynamicSnippetContent } from "./serviceDynamicSnippetContent";
import { ServiceVcl } from "./serviceVcl";
import { ServiceWafConfiguration } from "./serviceWafConfiguration";
import { TlsActivation } from "./tlsActivation";
import { TlsCertificate } from "./tlsCertificate";
import { TlsPlatformCertificate } from "./tlsPlatformCertificate";
import { TlsPrivateKey } from "./tlsPrivateKey";
import { TlsSubscription } from "./tlsSubscription";
import { TlsSubscriptionValidation } from "./tlsSubscriptionValidation";
import { User } from "./user";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "fastly:index/serviceACLEntries:ServiceACLEntries":
                return new ServiceACLEntries(name, <any>undefined, { urn })
            case "fastly:index/serviceAuthorization:ServiceAuthorization":
                return new ServiceAuthorization(name, <any>undefined, { urn })
            case "fastly:index/serviceCompute:ServiceCompute":
                return new ServiceCompute(name, <any>undefined, { urn })
            case "fastly:index/serviceDictionaryItems:ServiceDictionaryItems":
                return new ServiceDictionaryItems(name, <any>undefined, { urn })
            case "fastly:index/serviceDynamicSnippetContent:ServiceDynamicSnippetContent":
                return new ServiceDynamicSnippetContent(name, <any>undefined, { urn })
            case "fastly:index/serviceVcl:ServiceVcl":
                return new ServiceVcl(name, <any>undefined, { urn })
            case "fastly:index/serviceWafConfiguration:ServiceWafConfiguration":
                return new ServiceWafConfiguration(name, <any>undefined, { urn })
            case "fastly:index/tlsActivation:TlsActivation":
                return new TlsActivation(name, <any>undefined, { urn })
            case "fastly:index/tlsCertificate:TlsCertificate":
                return new TlsCertificate(name, <any>undefined, { urn })
            case "fastly:index/tlsPlatformCertificate:TlsPlatformCertificate":
                return new TlsPlatformCertificate(name, <any>undefined, { urn })
            case "fastly:index/tlsPrivateKey:TlsPrivateKey":
                return new TlsPrivateKey(name, <any>undefined, { urn })
            case "fastly:index/tlsSubscription:TlsSubscription":
                return new TlsSubscription(name, <any>undefined, { urn })
            case "fastly:index/tlsSubscriptionValidation:TlsSubscriptionValidation":
                return new TlsSubscriptionValidation(name, <any>undefined, { urn })
            case "fastly:index/user:User":
                return new User(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("fastly", "index/serviceACLEntries", _module)
pulumi.runtime.registerResourceModule("fastly", "index/serviceAuthorization", _module)
pulumi.runtime.registerResourceModule("fastly", "index/serviceCompute", _module)
pulumi.runtime.registerResourceModule("fastly", "index/serviceDictionaryItems", _module)
pulumi.runtime.registerResourceModule("fastly", "index/serviceDynamicSnippetContent", _module)
pulumi.runtime.registerResourceModule("fastly", "index/serviceVcl", _module)
pulumi.runtime.registerResourceModule("fastly", "index/serviceWafConfiguration", _module)
pulumi.runtime.registerResourceModule("fastly", "index/tlsActivation", _module)
pulumi.runtime.registerResourceModule("fastly", "index/tlsCertificate", _module)
pulumi.runtime.registerResourceModule("fastly", "index/tlsPlatformCertificate", _module)
pulumi.runtime.registerResourceModule("fastly", "index/tlsPrivateKey", _module)
pulumi.runtime.registerResourceModule("fastly", "index/tlsSubscription", _module)
pulumi.runtime.registerResourceModule("fastly", "index/tlsSubscriptionValidation", _module)
pulumi.runtime.registerResourceModule("fastly", "index/user", _module)

import { Provider } from "./provider";

pulumi.runtime.registerResourcePackage("fastly", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:fastly") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
