// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The provider type for the fastly package. By default, resources use package-wide configuration
 * settings, however an explicit `Provider` instance may be created and passed during resource
 * construction to achieve fine-grained programmatic control over provider settings. See the
 * [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
 */
export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'fastly';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Provider.__pulumiType;
    }

    /**
     * Fastly API Key from https://app.fastly.com/#account
     */
    public readonly apiKey!: pulumi.Output<string | undefined>;
    /**
     * Fastly API URL
     */
    public readonly baseUrl!: pulumi.Output<string | undefined>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            inputs["apiKey"] = args ? args.apiKey : undefined;
            inputs["baseUrl"] = args ? args.baseUrl : undefined;
            inputs["forceHttp2"] = pulumi.output(args ? args.forceHttp2 : undefined).apply(JSON.stringify);
            inputs["noAuth"] = pulumi.output(args ? args.noAuth : undefined).apply(JSON.stringify);
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(Provider.__pulumiType, name, inputs, opts);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * Fastly API Key from https://app.fastly.com/#account
     */
    apiKey?: pulumi.Input<string>;
    /**
     * Fastly API URL
     */
    baseUrl?: pulumi.Input<string>;
    /**
     * Set this to `true` to disable HTTP/1.x fallback mechanism that the underlying Go library will attempt upon connection to
     * `api.fastly.com:443` by default. This may slightly improve the provider's performance and reduce unnecessary TLS
     * handshakes. Default: `false`
     */
    forceHttp2?: pulumi.Input<boolean>;
    /**
     * Set this to `true` if you only need data source that does not require authentication such as `fastly_ip_ranges`
     */
    noAuth?: pulumi.Input<boolean>;
}
